-- Descrições personalizadas dos cursos de Pós-Graduação (coluna "descricao",
-- que aparece como "Sobre o curso" na página do curso).
-- Rode inteiro no SQL Editor do Supabase. Pode rodar de novo: só sobrescreve.

update public.courses c
set descricao = d.texto
from public.course_niveis n,
(values
  ('administracao-publica',
   'Com 570 horas, a pós-graduação em Administração Pública aprofunda o planejamento governamental, o orçamento público, as licitações e a gestão de políticas públicas. Uma especialização para servidores que querem crescer na carreira, ocupar cargos de gestão e para quem se prepara para concursos.'),
  ('agronegocios',
   'Em 570 horas, a pós-graduação em Agronegócios desenvolve uma visão estratégica de toda a cadeia do agro, da produção rural à comercialização, passando por gestão de custos, mercado, logística e sustentabilidade. Ideal para produtores, gestores de cooperativas e profissionais de empresas do setor.'),
  ('analise-do-comportamento-aplicada-aba-tea',
   'Com 420 horas, esta especialização aprofunda os fundamentos e as técnicas da Análise do Comportamento Aplicada (ABA) para planejar intervenções que desenvolvam comunicação, autonomia e habilidades sociais de pessoas com TEA. Voltada a psicólogos, pedagogos, terapeutas, mediadores e demais profissionais que atendem pessoas com autismo.'),
  ('antropologia',
   'Em 450 horas, a pós-graduação em Antropologia estuda as culturas, os modos de vida e as relações sociais, oferecendo ferramentas de pesquisa e análise da diversidade humana. Uma especialização para educadores, pesquisadores e profissionais que atuam em políticas públicas, projetos sociais e comunidades.'),
  ('arteterapia',
   'Com 570 horas, a pós-graduação em Arteterapia une arte e cuidado, capacitando você a usar pintura, modelagem, música e outras expressões artísticas como recursos de autoconhecimento e bem-estar. Indicada para profissionais da saúde, da educação e da assistência social que querem ampliar suas formas de acolhimento.'),
  ('atencao-e-cuidados-com-idosos',
   'Em 570 horas, a especialização em Atenção e Cuidados com Idosos aborda o processo de envelhecimento e as práticas de cuidado integral à pessoa idosa, com foco em saúde, prevenção, qualidade de vida e direitos. Uma área em crescimento para profissionais da saúde, cuidadores e quem atua em instituições de longa permanência.'),
  ('atendimento-educacional-especializado-com-enfase-em-autismo',
   'Com 420 horas, esta pós-graduação prepara educadores para planejar e conduzir o Atendimento Educacional Especializado (AEE) de estudantes com autismo, com estratégias pedagógicas, recursos de acessibilidade e trabalho articulado com a sala comum e a família. Ideal para professores de sala de recursos e da educação inclusiva.'),
  ('auditoria-em-saude',
   'Em 420 horas, a pós-graduação em Auditoria em Saúde capacita você para avaliar a qualidade, os custos e a conformidade dos serviços de saúde, analisando contas hospitalares, prontuários e contratos. Uma especialização valorizada em hospitais, operadoras de planos de saúde e órgãos de gestão pública.'),
  ('avaliacao-psicologica-e-psicodiagnostico',
   'Com 570 horas, esta especialização aprofunda o uso de testes, entrevistas e instrumentos de avaliação psicológica para a elaboração de psicodiagnósticos, laudos e pareceres. Voltada a psicólogos que querem mais segurança técnica na avaliação em contextos clínicos, escolares, organizacionais e jurídicos.'),
  ('biomedicina-estetica',
   'Em 420 horas, a pós-graduação em Biomedicina Estética aborda procedimentos estéticos faciais e corporais sob a perspectiva da biomedicina, com fundamentos de anatomia, fisiologia da pele, biossegurança e protocolos de tratamento. Indicada para biomédicos que querem atuar com segurança no mercado da estética.'),
  ('ciencias-da-religiao-com-enfase-em-docencia-do-ensino-superior',
   'Com 360 horas, esta pós-graduação estuda o fenômeno religioso de forma crítica e interdisciplinar e, ao mesmo tempo, prepara você para a docência no ensino superior, com didática e planejamento de aulas. Uma especialização para teólogos, educadores e lideranças religiosas que querem ensinar e pesquisar.'),
  ('compliance',
   'Em 570 horas, a pós-graduação em Compliance capacita você para estruturar programas de integridade nas organizações, com foco em normas regulatórias, prevenção à corrupção, controles internos e proteção de dados. Uma das áreas mais procuradas por empresas privadas, instituições financeiras e órgãos públicos.'),
  ('comportamento-humano-e-neurociencia',
   'Com 570 horas, esta especialização relaciona o funcionamento do cérebro com emoções, decisões e comportamentos, aplicando a neurociência ao dia a dia das pessoas e das organizações. Indicada para profissionais da saúde, da educação, da gestão de pessoas e do marketing.'),
  ('comunicacao-e-oratoria',
   'Em 570 horas, a pós-graduação em Comunicação e Oratória desenvolve a comunicação verbal e não verbal, a argumentação e a segurança para falar em público em apresentações, reuniões e negociações. Uma especialização para líderes, professores, vendedores e todos que querem se comunicar com mais impacto.'),
  ('criminologia',
   'Com 420 horas, a pós-graduação em Criminologia estuda o crime, o criminoso, a vítima e o controle social, oferecendo uma visão interdisciplinar sobre violência e políticas de segurança. Ideal para profissionais do Direito, das forças de segurança, da assistência social e para quem se prepara para concursos.'),
  ('cuidados-paliativos',
   'Em 420 horas, a especialização em Cuidados Paliativos prepara você para oferecer cuidado integral a pacientes com doenças graves e sem perspectiva de cura, com foco no controle de sintomas, na comunicação e no apoio à família. Uma formação humana e técnica para profissionais da saúde.'),
  ('diagnostico-e-avaliacao-psicologica',
   'Com 570 horas, esta pós-graduação aprofunda os métodos de investigação clínica e os instrumentos de avaliação psicológica, preparando para conduzir processos de diagnóstico com rigor técnico e ético. Voltada a psicólogos que atuam ou querem atuar em clínicas, escolas, hospitais e no contexto jurídico.'),
  ('didatica-do-ensino-de-lingua-portuguesa-inglesa-e-espanhola',
   'Em 390 horas, esta especialização apresenta metodologias e recursos didáticos para o ensino de português, inglês e espanhol, com foco em leitura, escrita, oralidade e práticas comunicativas. Ideal para professores de línguas que querem tornar suas aulas mais dinâmicas e eficazes.'),
  ('direito-administrativo',
   'Com 420 horas, a pós-graduação em Direito Administrativo aprofunda a organização e a atuação da Administração Pública, abordando atos administrativos, licitações, contratos, servidores e improbidade. Uma especialização para advogados, servidores públicos e quem se prepara para concursos.'),
  ('direito-ambiental',
   'Em 420 horas, a pós-graduação em Direito Ambiental estuda a legislação e os instrumentos de proteção ao meio ambiente, como licenciamento, responsabilidade por danos ambientais e crimes ambientais. Uma área em expansão para advogados, consultores, gestores e servidores de órgãos ambientais.'),
  ('direito-constitucional',
   'Com 420 horas, a pós-graduação em Direito Constitucional aprofunda o estudo da Constituição Federal, dos direitos e garantias fundamentais, da organização do Estado e do controle de constitucionalidade. Uma base sólida para advogados, servidores e candidatos a concursos públicos.'),
  ('direito-de-familia',
   'Em 420 horas, a especialização em Direito de Família aborda casamento, união estável, divórcio, guarda, alimentos, filiação e sucessões, com foco na prática jurídica e na mediação de conflitos familiares. Indicada para advogados e profissionais que atuam com demandas familiares.'),
  ('direito-de-transito',
   'Com 420 horas, a pós-graduação em Direito de Trânsito estuda o Código de Trânsito Brasileiro, infrações, penalidades, processos administrativos e crimes de trânsito. Uma especialização para advogados, agentes e gestores de órgãos de trânsito e profissionais da área de mobilidade.'),
  ('direito-do-trabalho-e-processual-trabalhista',
   'Em 420 horas, esta pós-graduação aprofunda as relações de emprego, os direitos trabalhistas, a reforma trabalhista e o processo do trabalho, da reclamação à execução. Ideal para advogados, profissionais de RH e departamento pessoal e candidatos a concursos da Justiça do Trabalho.'),
  ('direito-educacional',
   'Com 420 horas, a pós-graduação em Direito Educacional estuda a legislação da educação brasileira, incluindo a LDB, a regulação de instituições de ensino e os direitos de alunos e professores. Uma especialização para gestores escolares, advogados e profissionais de instituições de ensino.'),
  ('direito-eleitoral',
   'Em 420 horas, a pós-graduação em Direito Eleitoral aborda o sistema eleitoral brasileiro, partidos políticos, propaganda, prestação de contas, crimes eleitorais e o processo na Justiça Eleitoral. Indicada para advogados, assessores políticos, servidores e candidatos a concursos.'),
  ('direito-empresarial',
   'Com 420 horas, a especialização em Direito Empresarial estuda as sociedades empresárias, contratos mercantis, títulos de crédito, propriedade intelectual, recuperação judicial e falência. Uma formação para advogados, contadores, gestores e empreendedores que querem segurança jurídica nos negócios.'),
  ('direito-imobiliario',
   'Em 420 horas, a pós-graduação em Direito Imobiliário aborda compra e venda, locação, registro de imóveis, incorporação, condomínios e regularização fundiária, com foco na prática. Ideal para advogados, corretores, gestores de imobiliárias e profissionais de cartórios.'),
  ('direito-penal-e-processual-penal',
   'Com 420 horas, esta pós-graduação aprofunda a teoria do crime, as penas e o processo penal, da investigação ao julgamento e aos recursos, com foco na prática da advocacia criminal. Uma especialização também valorizada por quem se prepara para concursos das carreiras jurídicas e policiais.'),
  ('direito-penal-militar',
   'Em 420 horas, a pós-graduação em Direito Penal Militar estuda os crimes militares, o Código Penal Militar, a organização da Justiça Militar e o processo penal militar. Indicada para militares, advogados que atuam na área e candidatos a concursos das carreiras militares.'),
  ('direito-previdenciario',
   'Com 420 horas, a especialização em Direito Previdenciário aborda os benefícios do INSS e dos regimes próprios, aposentadorias, cálculos, planejamento previdenciário e o processo administrativo e judicial. Uma área com grande demanda para advogados e profissionais de assessoria previdenciária.'),
  ('direito-processual-civil',
   'Em 420 horas, a pós-graduação em Direito Processual Civil aprofunda o Código de Processo Civil, do ajuizamento da ação aos recursos e ao cumprimento de sentença, com foco na prática forense. Ideal para advogados, servidores do Judiciário e candidatos a concursos.'),
  ('direito-publico-constitucional-administrativo-e-tributario',
   'Com 420 horas, esta pós-graduação integra os três principais ramos do Direito Público: a Constituição, a atuação da Administração Pública e o sistema tributário. Uma especialização completa para advogados, servidores públicos e quem se prepara para concursos das carreiras jurídicas.'),
  ('direito-tributario',
   'Em 420 horas, a pós-graduação em Direito Tributário estuda o sistema tributário nacional, os tributos federais, estaduais e municipais, o planejamento tributário e o contencioso fiscal. Uma área estratégica para advogados, contadores e gestores de empresas.'),
  ('direitos-humanos-e-pericia-criminal',
   'Com 420 horas, esta especialização une a proteção dos direitos humanos às técnicas de investigação e perícia criminal, abordando cadeia de custódia, criminalística e produção de provas. Indicada para profissionais da segurança pública, do Direito e candidatos a concursos da área policial.'),
  ('docencia-em-enfermagem',
   'Em 420 horas, a pós-graduação em Docência em Enfermagem prepara enfermeiros para ensinar em cursos técnicos e de graduação, com didática, planejamento de aulas, avaliação e supervisão de estágios. Uma especialização para quem quer unir a prática profissional à carreira de professor.'),
  ('educacao-ambiental-e-sustentabilidade',
   'Com 360 horas, esta pós-graduação capacita você para desenvolver projetos e práticas de educação ambiental em escolas, empresas e comunidades, promovendo a consciência ecológica e o consumo responsável. Ideal para educadores, gestores e profissionais da área ambiental.'),
  ('educacao-especial-e-inclusiva',
   'Em 360 horas, a especialização em Educação Especial e Inclusiva prepara você para promover a inclusão de estudantes com deficiência, transtornos e altas habilidades, com adaptações curriculares, recursos de acessibilidade e práticas pedagógicas diversificadas. Uma formação essencial para professores e gestores escolares.'),
  ('educacao-especial-inclusiva-e-tea',
   'Com 360 horas, esta pós-graduação une os fundamentos da educação inclusiva ao estudo do autismo, com estratégias para acolher, ensinar e acompanhar estudantes com TEA no ambiente escolar. Indicada para professores, mediadores, coordenadores e profissionais de apoio escolar.'),
  ('enfermagem-do-trabalho-e-saude-ocupacional',
   'Em 420 horas, esta especialização prepara enfermeiros para atuar na promoção da saúde e na prevenção de doenças e acidentes no ambiente de trabalho, com programas de saúde ocupacional e normas regulamentadoras. Uma área com espaço em indústrias, empresas e serviços de medicina do trabalho.'),
  ('enfermagem-em-urgencia-e-emergencia',
   'Com 420 horas, a pós-graduação em Enfermagem em Urgência e Emergência capacita enfermeiros para o atendimento rápido e seguro a pacientes em situações críticas, em prontos-socorros, UPAs e no atendimento pré-hospitalar. Uma especialização muito procurada pelos serviços de saúde.'),
  ('enfermagem-oncologica',
   'Em 450 horas, a especialização em Enfermagem Oncológica aprofunda o cuidado ao paciente com câncer, abrangendo quimioterapia, radioterapia, manejo de sintomas e apoio ao paciente e à família. Indicada para enfermeiros que atuam ou querem atuar em hospitais e centros de oncologia.'),
  ('engenharia-ambiental',
   'Com 570 horas, a pós-graduação em Engenharia Ambiental aborda o diagnóstico, o controle e a recuperação de impactos ambientais, com gestão de resíduos, tratamento de efluentes e licenciamento. Uma especialização para engenheiros e profissionais que atuam em indústrias, consultorias e órgãos ambientais.'),
  ('engenharia-ambiental-e-saneamento-basico',
   'Em 570 horas, esta pós-graduação une a gestão ambiental aos sistemas de saneamento, abordando abastecimento de água, esgotamento sanitário, drenagem urbana e resíduos sólidos. Ideal para profissionais que atuam em companhias de saneamento, prefeituras, consultorias e projetos de infraestrutura.'),
  ('engenharia-da-qualidade',
   'Com 570 horas, a pós-graduação em Engenharia da Qualidade capacita você para implantar e melhorar sistemas de qualidade, com ferramentas estatísticas, normas ISO, controle de processos e melhoria contínua. Uma especialização valorizada em indústrias e empresas de serviços.'),
  ('engenharia-de-manutencao',
   'Em 570 horas, a pós-graduação em Engenharia de Manutenção aborda a gestão da manutenção preventiva, preditiva e corretiva, com foco em confiabilidade, disponibilidade de equipamentos e redução de custos. Indicada para engenheiros, técnicos e gestores de manutenção industrial.'),
  ('engenharia-de-producao',
   'Com 570 horas, a pós-graduação em Engenharia de Produção desenvolve competências para planejar, controlar e otimizar sistemas produtivos, integrando pessoas, processos, tecnologia e qualidade. Uma especialização para quem atua ou quer atuar na gestão de operações industriais e de serviços.'),
  ('engenharia-de-seguranca-do-trabalho',
   'Em 570 horas, esta pós-graduação aprofunda a identificação, a avaliação e o controle de riscos ocupacionais, com normas regulamentadoras, higiene ocupacional, prevenção de acidentes e combate a incêndios. Voltada a engenheiros e arquitetos que querem atuar na segurança do trabalho.'),
  ('engenharia-de-suprimentos',
   'Com 570 horas, a pós-graduação em Engenharia de Suprimentos capacita você para gerenciar compras, estoques e relacionamento com fornecedores, otimizando a cadeia de suprimentos com foco em custo, prazo e qualidade. Ideal para profissionais de compras, logística e operações.'),
  ('engenharia-logistica',
   'Em 570 horas, a pós-graduação em Engenharia Logística aborda o planejamento e a otimização de transporte, armazenagem e distribuição, com modelagem de redes logísticas e indicadores de desempenho. Uma especialização para quem atua em indústrias, transportadoras, centros de distribuição e e-commerce.'),
  ('engenharia-sanitaria-e-ambiental',
   'Com 570 horas, esta pós-graduação estuda sistemas de tratamento de água e esgoto, gestão de resíduos e controle da poluição, com foco na saúde pública e na preservação ambiental. Indicada para engenheiros e profissionais de saneamento, meio ambiente e infraestrutura urbana.'),
  ('ensino-da-literatura-africana-e-indigena',
   'Em 360 horas, esta especialização prepara educadores para trabalhar em sala de aula as literaturas africanas, afro-brasileiras e indígenas, valorizando a diversidade cultural e atendendo à legislação sobre o ensino da história e da cultura desses povos. Ideal para professores de todas as etapas da educação básica.'),
  ('estatistica-aplicada',
   'Com 570 horas, a pós-graduação em Estatística Aplicada capacita você para coletar, analisar e interpretar dados com métodos estatísticos, apoiando decisões em negócios, pesquisas e políticas públicas. Uma especialização valorizada em empresas, institutos de pesquisa e áreas de análise de dados.'),
  ('estetica-corporal-e-facial',
   'Em 420 horas, a pós-graduação em Estética Corporal e Facial aborda protocolos de tratamentos faciais e corporais, recursos eletroterapêuticos, cosméticos e avaliação estética. Uma especialização para profissionais da estética e da saúde que querem oferecer tratamentos mais completos e seguros.'),
  ('estetica-e-cosmetologia',
   'Com 480 horas, esta pós-graduação une o estudo dos cosméticos, seus ativos e formulações às práticas de estética, para indicar e aplicar tratamentos com mais segurança e resultado. Indicada para esteticistas, profissionais da saúde e quem atua na indústria e no comércio de cosméticos.'),
  ('expressoes-artisticas-e-suas-representacoes',
   'Em 450 horas, esta especialização explora as linguagens artísticas, como artes visuais, música, dança e teatro, e seus significados culturais, com aplicações na educação e em projetos culturais. Ideal para professores de arte, educadores e produtores culturais.'),
  ('farmacia-clinica-e-hospitalar',
   'Com 420 horas, a pós-graduação em Farmácia Clínica e Hospitalar prepara farmacêuticos para o cuidado ao paciente e a gestão da farmácia hospitalar, com foco no uso racional de medicamentos, farmacovigilância e segurança do paciente. Uma especialização valorizada em hospitais e clínicas.'),
  ('farmacologia-clinica-aplicada-a-prescricao-farmaceutica',
   'Em 420 horas, esta pós-graduação aprofunda a farmacologia aplicada à prescrição farmacêutica, com avaliação clínica, escolha terapêutica e acompanhamento do paciente dentro das atribuições do farmacêutico. Indicada para farmacêuticos que atuam em drogarias, consultórios e serviços de saúde.'),
  ('fisioterapia-aplicada-as-atividades-fisicas',
   'Com 420 horas, esta especialização aborda a prevenção e a reabilitação de lesões relacionadas ao exercício e ao esporte, com avaliação funcional e recursos terapêuticos. Voltada a fisioterapeutas que atuam ou querem atuar com atletas, academias e clínicas esportivas.'),
  ('fisioterapia-em-geriatria-e-gerontologia',
   'Em 480 horas, a pós-graduação em Fisioterapia em Geriatria e Gerontologia prepara fisioterapeutas para o cuidado da pessoa idosa, com foco em prevenção de quedas, mobilidade, funcionalidade e qualidade de vida. Uma área em crescimento com o envelhecimento da população.'),
  ('geologia-e-hidrologia',
   'Com 510 horas, a pós-graduação em Geologia e Hidrologia estuda a formação e a dinâmica dos solos, das rochas e dos recursos hídricos, com aplicações em gestão ambiental, obras e uso sustentável da água. Ideal para profissionais das áreas ambiental, de engenharia e de recursos naturais.'),
  ('gestao-bancaria-e-negocios',
   'Em 570 horas, a pós-graduação em Gestão Bancária e Negócios capacita você para atuar no mercado financeiro e bancário, com produtos e serviços financeiros, análise de crédito, investimentos e relacionamento com clientes. Uma especialização para bancários e profissionais de instituições financeiras.'),
  ('gestao-da-qualidade',
   'Com 570 horas, a pós-graduação em Gestão da Qualidade prepara você para implantar e gerenciar sistemas de qualidade, com normas ISO, indicadores, auditorias e melhoria contínua de processos. Uma especialização valorizada em indústrias, empresas de serviços e instituições de saúde.'),
  ('gestao-de-recursos-humanos',
   'Em 570 horas, a pós-graduação em Gestão de Recursos Humanos aborda recrutamento, seleção, treinamento, avaliação de desempenho, remuneração e clima organizacional, com visão estratégica. Ideal para profissionais de RH e gestores que querem valorizar o capital humano da empresa.'),
  ('gestao-de-riscos-e-ciberseguranca',
   'Com 400 horas, a pós-graduação em Gestão de Riscos e Cibersegurança capacita você para identificar e tratar riscos digitais, proteger dados e sistemas e estruturar políticas de segurança da informação. Uma das áreas mais procuradas da tecnologia, com espaço em empresas de todos os setores.'),
  ('gestao-e-planejamento-de-projetos-sociais',
   'Em 570 horas, esta pós-graduação prepara você para elaborar, captar recursos, executar e avaliar projetos sociais em ONGs, empresas e órgãos públicos. Uma especialização para quem quer transformar realidades com planejamento, transparência e resultados mensuráveis.'),
  ('gestao-educacional-com-foco-na-inclusao',
   'Com 360 horas, esta especialização capacita gestores escolares para conduzir instituições inclusivas, com planejamento, políticas de acessibilidade, formação de equipes e envolvimento das famílias. Indicada para diretores, coordenadores e professores que querem assumir funções de gestão.'),
  ('gestao-estrategica-de-pessoas',
   'Em 570 horas, a pós-graduação em Gestão Estratégica de Pessoas alinha a gestão de pessoas aos objetivos da organização, com desenvolvimento de talentos, liderança, cultura organizacional e indicadores de RH. Ideal para gestores e profissionais de RH com visão de negócio.'),
  ('gestao-hospitalar',
   'Com 570 horas, a pós-graduação em Gestão Hospitalar prepara você para administrar hospitais e serviços de saúde, com gestão financeira, de pessoas e de suprimentos, qualidade e segurança do paciente. Uma especialização com demanda constante na rede pública e privada de saúde.'),
  ('libras',
   'Em 360 horas, a pós-graduação em Libras desenvolve a comunicação em Língua Brasileira de Sinais e aborda a cultura surda e a educação bilíngue, promovendo a inclusão da pessoa surda. Indicada para professores, intérpretes em formação e profissionais que atendem o público.'),
  ('lideranca-e-desenvolvimento-de-equipes',
   'Com 450 horas, esta especialização desenvolve habilidades de liderança, comunicação, feedback e gestão de conflitos para formar e conduzir equipes de alto desempenho. Ideal para quem já lidera ou quer se preparar para assumir cargos de gestão.'),
  ('ludopedagogia',
   'Em 360 horas, a pós-graduação em Ludopedagogia explora o brincar, os jogos e as atividades lúdicas como ferramentas de aprendizagem e desenvolvimento, com aplicações na educação infantil e no ensino fundamental. Uma especialização para professores, pedagogos e recreadores.'),
  ('matematica-financeira-e-estatistica',
   'Com 570 horas, esta pós-graduação aprofunda juros, descontos, financiamentos, análise de investimentos e métodos estatísticos aplicados à tomada de decisão. Indicada para profissionais de finanças, bancos, contabilidade, professores de matemática e gestores.'),
  ('mba-em-administracao-financeira-e-orcamentaria',
   'Em 570 horas, o MBA em Administração Financeira e Orçamentária capacita você para planejar e controlar as finanças da organização, com elaboração de orçamentos, análise de demonstrativos e gestão do fluxo de caixa. Ideal para profissionais de finanças, controladoria e gestores.'),
  ('mba-em-arbitragem-conciliacao-e-mediacao',
   'Com 570 horas, o MBA em Arbitragem, Conciliação e Mediação prepara você para conduzir métodos consensuais e extrajudiciais de solução de conflitos, com técnicas de negociação e comunicação. Uma especialização para advogados, gestores e profissionais que lidam com disputas.'),
  ('mba-em-assessoria-de-comunicacao',
   'Em 570 horas, o MBA em Assessoria de Comunicação aborda relacionamento com a imprensa, comunicação corporativa, gestão de crises e planejamento de comunicação integrada. Indicado para jornalistas, relações-públicas, publicitários e profissionais de comunicação.'),
  ('mba-em-coaching',
   'Com 570 horas, o MBA em Coaching desenvolve ferramentas e metodologias para apoiar pessoas e equipes no alcance de metas, no desenvolvimento de competências e na transição de carreira. Ideal para líderes, profissionais de RH e quem quer atuar como coach.'),
  ('mba-em-compliance-e-gestao-de-riscos',
   'Em 570 horas, o MBA em Compliance e Gestão de Riscos capacita você para estruturar programas de integridade e gerenciar riscos corporativos, com controles internos, auditoria e adequação às normas. Uma especialização muito valorizada por empresas e instituições financeiras.'),
  ('mba-em-comunicacao-eleitoral-e-marketing-politico',
   'Com 570 horas, o MBA em Comunicação Eleitoral e Marketing Político aborda estratégias de campanha, pesquisa eleitoral, construção de imagem, comunicação digital e legislação eleitoral. Indicado para profissionais de comunicação, assessores e quem atua ou quer atuar em campanhas.'),
  ('mba-em-contabilidade-gerencial',
   'Em 570 horas, o MBA em Contabilidade Gerencial prepara você para usar a informação contábil na gestão, com análise de custos, orçamento, indicadores de desempenho e apoio à tomada de decisão. Ideal para contadores, controllers e gestores.'),
  ('mba-em-controladoria-e-financas',
   'Com 570 horas, o MBA em Controladoria e Finanças capacita você para atuar na controladoria, com planejamento financeiro, controles internos, análise de resultados e gestão de riscos. Uma especialização para contadores, administradores e profissionais da área financeira.'),
  ('mba-em-e-commerce',
   'Em 570 horas, o MBA em E-commerce aborda a gestão de lojas virtuais e marketplaces, com marketing digital, logística, meios de pagamento, experiência do cliente e análise de resultados. Indicado para empreendedores e profissionais que querem vender mais no ambiente digital.'),
  ('mba-em-educacao-financeira',
   'Com 570 horas, o MBA em Educação Financeira capacita você para orientar pessoas, famílias e organizações sobre orçamento, consumo consciente, endividamento, investimentos e planejamento financeiro. Ideal para professores, consultores e profissionais de finanças.'),
  ('mba-em-gestao-ambiental-e-sustentavel',
   'Em 570 horas, o MBA em Gestão Ambiental e Sustentável prepara você para integrar a sustentabilidade à estratégia das organizações, com sistemas de gestão ambiental, práticas ESG e legislação. Uma especialização em alta para gestores, consultores e profissionais da área ambiental.'),
  ('mba-em-gestao-aplicada-a-engenharia',
   'Com 570 horas, o MBA em Gestão Aplicada à Engenharia desenvolve competências de gestão para profissionais da engenharia, com gerenciamento de projetos, custos, equipes e contratos. Ideal para engenheiros que querem assumir cargos de coordenação e liderança.'),
  ('mba-em-gestao-comercial-e-vendas',
   'Em 570 horas, o MBA em Gestão Comercial e Vendas capacita você para liderar equipes comerciais, estruturar processos de vendas, negociar e gerenciar o relacionamento com clientes. Uma especialização para vendedores, supervisores e gestores comerciais que querem bater metas.'),
  ('mba-em-gestao-da-saude-publica',
   'Com 570 horas, o MBA em Gestão da Saúde Pública capacita você para gerir serviços e políticas de saúde pública, com organização do SUS, planejamento, financiamento e indicadores de saúde. Ideal para profissionais e gestores das secretarias e unidades de saúde.'),
  ('mba-em-gestao-de-clinicas-e-consultorios-veterinarios',
   'Em 570 horas, este MBA prepara você para administrar clínicas e consultórios veterinários, com gestão financeira, marketing, atendimento ao cliente e liderança de equipes. Indicado para médicos-veterinários e gestores que querem fazer o negócio crescer.'),
  ('mba-em-gestao-de-custo-e-financas',
   'Com 570 horas, o MBA em Gestão de Custo e Finanças aborda métodos de custeio, formação de preços, análise de margens e gestão financeira para aumentar a rentabilidade das empresas. Ideal para gestores, contadores, empreendedores e profissionais de finanças.'),
  ('mba-em-gestao-de-departamento-pessoal-e-relacoes-trabalhistas',
   'Em 570 horas, este MBA capacita você para conduzir as rotinas de departamento pessoal, como admissão, folha de pagamento, eSocial e rescisões, com segurança nas relações trabalhistas. Uma especialização para profissionais de DP, RH e escritórios de contabilidade.'),
  ('mba-em-gestao-de-drogaria-e-farmacia',
   'Com 570 horas, o MBA em Gestão de Drogaria e Farmácia prepara você para administrar farmácias e drogarias, com gestão de estoque, compras, atendimento, finanças, equipe e legislação sanitária. Indicado para farmacêuticos, gerentes e proprietários.'),
  ('mba-em-gestao-de-eventos',
   'Em 570 horas, o MBA em Gestão de Eventos aborda o planejamento, a captação de patrocínio, a produção e a avaliação de eventos corporativos, sociais, culturais e esportivos. Ideal para produtores, organizadores e profissionais de marketing e comunicação.'),
  ('mba-em-gestao-de-marketing-digital',
   'Com 570 horas, o MBA em Gestão de Marketing Digital capacita você para planejar e gerenciar estratégias digitais, com mídia paga, SEO, redes sociais, conteúdo, automação e análise de métricas. Uma especialização para profissionais de marketing, comunicação e empreendedores.'),
  ('mba-em-gestao-de-negocios-imobiliarios',
   'Em 510 horas, o MBA em Gestão de Negócios Imobiliários prepara você para atuar no mercado imobiliário, com avaliação de imóveis, incorporação, financiamento, gestão de carteiras e vendas. Indicado para corretores, gestores de imobiliárias e investidores.'),
  ('mba-em-gestao-de-obras-qualidade-e-desempenho-das-construcoes',
   'Com 570 horas, este MBA aborda o planejamento, o controle de custos e prazos e a gestão da qualidade em obras, com foco no desempenho das construções e nas normas técnicas. Ideal para engenheiros, arquitetos e gestores de construtoras.'),
  ('mba-em-gestao-de-pessoas-e-lideranca',
   'Em 570 horas, o MBA em Gestão de Pessoas e Liderança desenvolve competências de liderança e gestão de pessoas, com foco em engajamento, desenvolvimento de equipes, comunicação e cultura organizacional. Uma especialização para gestores e profissionais de RH.'),
  ('mba-em-gestao-de-processos',
   'Com 570 horas, o MBA em Gestão de Processos capacita você para mapear, analisar e redesenhar processos organizacionais, com metodologias como BPM e Lean e uso de indicadores. Ideal para analistas, gestores e consultores que buscam eficiência nas operações.'),
  ('mba-em-gestao-de-projetos',
   'Em 570 horas, o MBA em Gestão de Projetos prepara você para planejar, executar e controlar projetos com base nas boas práticas do PMBOK e em metodologias ágeis. Uma especialização valorizada em empresas de tecnologia, engenharia, serviços e no setor público.'),
  ('mba-em-gestao-de-seguros-e-previdencia-privada',
   'Com 570 horas, este MBA aborda o mercado de seguros e de previdência complementar, com produtos, regulação, gestão de riscos, noções atuariais e vendas. Indicado para corretores, profissionais de seguradoras e consultores financeiros.'),
  ('mba-em-gestao-de-supply-chain',
   'Em 570 horas, o MBA em Gestão de Supply Chain capacita você para integrar compras, produção, estoques e distribuição, gerenciando a cadeia de suprimentos com foco em custo, nível de serviço e competitividade. Ideal para profissionais de logística, compras e operações.'),
  ('mba-em-gestao-estrategica-de-cooperativas',
   'Com 570 horas, este MBA prepara você para administrar cooperativas, com governança, legislação cooperativista, gestão financeira e desenvolvimento dos cooperados. Indicado para dirigentes, gestores e colaboradores de cooperativas de crédito, agro, saúde e outros ramos.'),
  ('mba-em-gestao-estrategica-em-compras',
   'Em 570 horas, o MBA em Gestão Estratégica em Compras capacita você para estruturar a área de compras, com seleção e negociação com fornecedores, gestão de contratos, redução de custos e análise de mercado. Ideal para compradores, gestores de suprimentos e empreendedores.'),
  ('mba-em-gestao-financeira-e-controladoria',
   'Com 570 horas, o MBA em Gestão Financeira e Controladoria aborda planejamento financeiro, análise de investimentos, orçamento, controles internos e relatórios gerenciais. Uma especialização para profissionais de finanças, contabilidade e gestão que apoiam decisões estratégicas.'),
  ('mba-em-gestao-fiscal-e-tributaria',
   'Em 570 horas, o MBA em Gestão Fiscal e Tributária prepara você para gerenciar as obrigações fiscais das empresas, com apuração de tributos, obrigações acessórias, SPED e planejamento tributário. Indicado para contadores, analistas fiscais e gestores.'),
  ('mba-em-jornalismo-digital',
   'Com 570 horas, o MBA em Jornalismo Digital aborda a produção de notícias para plataformas digitais, com apuração, multimídia, redes sociais, SEO, checagem de fatos e novos modelos de negócio. Ideal para jornalistas e comunicadores que querem se destacar no ambiente digital.'),
  ('mba-em-marketing-de-varejo-gestao-estrategias-e-negocios',
   'Em 570 horas, este MBA capacita você para desenvolver estratégias de marketing no varejo, com gestão de categorias, trade marketing, experiência de compra e análise do consumidor. Indicado para gestores de lojas, profissionais de marketing e empreendedores do comércio.'),
  ('mba-em-marketing-digital-e-comunicacao-online',
   'Com 570 horas, este MBA prepara você para planejar a presença digital de marcas, com redes sociais, marketing de conteúdo, anúncios online, influência digital e métricas. Ideal para profissionais de marketing, comunicação, social media e empreendedores.'),
  ('mba-em-negocios-internacionais-e-comercio-exterior',
   'Em 570 horas, este MBA aborda importação, exportação, logística internacional, câmbio, tributação e estratégias de internacionalização de empresas. Uma especialização para profissionais de comércio exterior, logística, trading companies e empresas que querem conquistar novos mercados.'),
  ('mba-em-planejamento-e-gestao-no-transito',
   'Com 570 horas, o MBA em Planejamento e Gestão no Trânsito capacita você para planejar e gerir o trânsito e a mobilidade urbana, com engenharia de tráfego, fiscalização, educação e segurança viária. Indicado para profissionais de órgãos de trânsito, prefeituras e empresas de transporte.'),
  ('mba-em-startups-e-inovacao',
   'Em 570 horas, o MBA em Startups e Inovação prepara você para criar e gerir negócios inovadores, com modelagem de negócios, validação de ideias, métodos ágeis, captação de investimento e crescimento. Ideal para empreendedores e profissionais que querem inovar dentro das empresas.'),
  ('medicinas-e-terapias-alternativas',
   'Com 510 horas, esta pós-graduação apresenta os fundamentos das práticas integrativas e complementares, como fitoterapia, aromaterapia e acupuntura, e seu papel como apoio ao cuidado em saúde. Indicada para profissionais da saúde e do bem-estar que querem ampliar sua atuação de forma responsável.'),
  ('metodologia-do-ensino-de-ingles',
   'Em 360 horas, esta especialização apresenta abordagens e técnicas para o ensino da língua inglesa, com foco no desenvolvimento da compreensão, da fala, da leitura e da escrita. Ideal para professores de inglês de escolas regulares e de idiomas.'),
  ('metodologia-do-ensino-de-lingua-portuguesa',
   'Com 360 horas, esta pós-graduação aborda práticas de ensino de leitura, produção de texto, gramática e oralidade, alinhadas à BNCC e às necessidades dos alunos de hoje. Uma especialização para professores de língua portuguesa da educação básica.'),
  ('metodologia-do-ensino-linguistico',
   'Em 360 horas, esta especialização estuda teorias da linguagem e sua aplicação em sala de aula, com estratégias para o ensino de línguas e o desenvolvimento das competências comunicativas. Indicada para professores de línguas e profissionais da educação.'),
  ('metodologia-do-ensino-superior-nas-varias-modalidades',
   'Com 360 horas, esta pós-graduação prepara você para a docência no ensino superior presencial, semipresencial e a distância, com planejamento, didática, avaliação e uso de tecnologias. Ideal para profissionais de todas as áreas que querem dar aulas em faculdades e universidades.'),
  ('metodologias-ativas-e-pratica-docente',
   'Em 360 horas, esta especialização apresenta metodologias ativas, como sala de aula invertida, aprendizagem baseada em projetos e gamificação, para tornar o aluno protagonista da aprendizagem. Indicada para professores de todos os níveis de ensino.'),
  ('metodologias-ativas-e-tecnologias-educacionais',
   'Com 360 horas, esta pós-graduação une metodologias ativas ao uso de ferramentas digitais, plataformas e recursos tecnológicos para criar aulas mais participativas e significativas. Ideal para professores, coordenadores e profissionais de educação corporativa.'),
  ('microbiologia',
   'Em 420 horas, a pós-graduação em Microbiologia aprofunda o estudo de bactérias, fungos, vírus e parasitas, com técnicas laboratoriais e aplicações em saúde, alimentos e meio ambiente. Indicada para biomédicos, biólogos, farmacêuticos e profissionais de laboratório.'),
  ('neuroeducacao',
   'Com 390 horas, a pós-graduação em Neuroeducação integra neurociência e educação para compreender como o cérebro aprende e aplicar esse conhecimento em estratégias de ensino mais eficazes. Uma especialização para professores, pedagogos e profissionais da educação.'),
  ('neuropsicologia-clinica',
   'Em 570 horas, a pós-graduação em Neuropsicologia Clínica aprofunda a relação entre cérebro, cognição e comportamento, com avaliação neuropsicológica e reabilitação das funções cognitivas. Voltada a psicólogos e profissionais da saúde que atuam com transtornos neurológicos e do desenvolvimento.'),
  ('neuropsicopedagogia-clinica',
   'Com 570 horas, esta especialização integra neurociência, psicologia e pedagogia para avaliar e intervir nas dificuldades e nos transtornos de aprendizagem em contexto clínico. Indicada para pedagogos, psicopedagogos, psicólogos e profissionais da educação.'),
  ('nutricao-esportiva',
   'Em 420 horas, a pós-graduação em Nutrição Esportiva aborda as necessidades nutricionais de praticantes de atividade física e atletas, com estratégias alimentares, suplementação e avaliação corporal. Voltada a nutricionistas que querem atuar com esporte e performance.'),
  ('orientacao-educacional',
   'Com 360 horas, a pós-graduação em Orientação Educacional prepara você para acompanhar o desenvolvimento dos estudantes, mediar as relações entre escola, família e comunidade e apoiar a convivência escolar. Ideal para pedagogos e professores que querem atuar na orientação.'),
  ('pericia-e-auditoria-contabil',
   'Em 570 horas, esta pós-graduação capacita você para realizar perícias contábeis judiciais e extrajudiciais e auditorias, com análise de demonstrações, elaboração de laudos e normas profissionais. Indicada para contadores que querem atuar como peritos e auditores.'),
  ('pericia-economica-financeira',
   'Com 570 horas, esta especialização prepara você para atuar em perícias que envolvem cálculos financeiros, revisão de contratos, avaliação de empresas e liquidação de sentenças. Ideal para economistas, contadores, administradores e advogados.'),
  ('projetos-pedagogicos',
   'Em 360 horas, a pós-graduação em Projetos Pedagógicos capacita você para elaborar, implementar e avaliar projetos pedagógicos e o projeto político-pedagógico da escola, com participação da comunidade escolar. Indicada para professores, coordenadores e gestores.'),
  ('psicanalise-clinica',
   'Com 480 horas, a pós-graduação em Psicanálise Clínica estuda a teoria psicanalítica de Freud e de seus sucessores, abordando inconsciente, sintoma, transferência e a condução do processo clínico. Uma especialização para psicólogos e profissionais que querem aprofundar a escuta psicanalítica.'),
  ('psicologia-clinica',
   'Em 570 horas, a pós-graduação em Psicologia Clínica aprofunda as principais abordagens teóricas e técnicas da psicoterapia, com foco no atendimento clínico, na avaliação e no manejo de casos. Voltada a psicólogos que querem mais segurança no consultório.'),
  ('psicologia-clinica-e-institucional',
   'Com 570 horas, esta especialização une a atuação clínica ao trabalho em instituições como escolas, hospitais, empresas e serviços sociais, com intervenções individuais e em grupo. Indicada para psicólogos que querem ampliar seus campos de atuação.'),
  ('psicologia-da-educacao',
   'Em 570 horas, a pós-graduação em Psicologia da Educação estuda os processos de desenvolvimento e aprendizagem e os fatores emocionais e sociais envolvidos, com aplicações no cotidiano escolar. Ideal para professores, pedagogos, psicólogos e gestores educacionais.'),
  ('psicologia-hospitalar',
   'Com 570 horas, a pós-graduação em Psicologia Hospitalar prepara você para o acompanhamento psicológico de pacientes, familiares e equipes no ambiente hospitalar, lidando com adoecimento, internação e luto. Voltada a psicólogos que atuam ou querem atuar em hospitais.'),
  ('psicologia-organizacional-do-trabalho',
   'Em 570 horas, esta pós-graduação aborda o comportamento humano nas organizações, com recrutamento, seleção, clima organizacional, saúde mental no trabalho e desenvolvimento de pessoas. Indicada para psicólogos, profissionais de RH e gestores.'),
  ('psicomotricidade',
   'Com 570 horas, a pós-graduação em Psicomotricidade estuda a relação entre movimento, emoção e cognição, com avaliação e intervenção psicomotora em contextos educacionais e clínicos. Ideal para pedagogos, professores de educação física, fisioterapeutas e terapeutas.'),
  ('psicomotricidade-e-ludopedagogia',
   'Em 390 horas, esta especialização une o desenvolvimento psicomotor às atividades lúdicas, com jogos e brincadeiras que estimulam corpo, cognição e afetividade. Indicada para professores da educação infantil e dos anos iniciais, pedagogos e recreadores.'),
  ('psicomotricidade-na-educacao-infantil',
   'Com 570 horas, esta pós-graduação aborda o desenvolvimento motor, cognitivo e afetivo das crianças pequenas, com práticas psicomotoras aplicadas à rotina da educação infantil. Ideal para professores, pedagogos e profissionais que atuam com a primeira infância.'),
  ('psicopedagogia-clinica-e-institucional',
   'Em 570 horas, a pós-graduação em Psicopedagogia Clínica e Institucional prepara você para avaliar e intervir nas dificuldades de aprendizagem, tanto no atendimento clínico quanto em escolas e outras instituições. Uma especialização para pedagogos, professores e psicólogos.'),
  ('psicopedagogia-escolar',
   'Com 390 horas, a pós-graduação em Psicopedagogia Escolar capacita você para identificar e prevenir dificuldades de aprendizagem no ambiente escolar, apoiando professores, alunos e famílias. Indicada para professores, coordenadores e pedagogos.'),
  ('relacoes-internacionais',
   'Em 570 horas, a pós-graduação em Relações Internacionais estuda a política internacional, a diplomacia, os organismos internacionais e o comércio global, com análise de cenários. Ideal para profissionais de comércio exterior, órgãos públicos, ONGs e empresas com atuação internacional.'),
  ('seguranca-da-informacao',
   'Com 570 horas, a pós-graduação em Segurança da Informação capacita você para proteger dados, sistemas e redes, com gestão de riscos, políticas de segurança, resposta a incidentes e proteção de dados pessoais. Uma especialização com alta demanda em empresas de todos os setores.'),
  ('seguranca-publica',
   'Em 570 horas, a pós-graduação em Segurança Pública aborda políticas de segurança, prevenção da violência, inteligência e gestão das instituições policiais. Indicada para profissionais das forças de segurança, gestores públicos e candidatos a concursos da área.'),
  ('seguranca-publica-e-cidadania',
   'Com 570 horas, esta especialização relaciona segurança pública e cidadania, com policiamento comunitário, mediação de conflitos, direitos humanos e participação social. Ideal para profissionais da segurança, da assistência social e de órgãos públicos.'),
  ('servico-social-e-convivencia-familiar',
   'Em 570 horas, esta pós-graduação prepara você para atuar na proteção e no fortalecimento de vínculos familiares e comunitários, com políticas de assistência social, acolhimento e garantia de direitos. Indicada para assistentes sociais, psicólogos e profissionais da rede de proteção.'),
  ('servico-social-na-educacao',
   'Com 360 horas, a pós-graduação em Serviço Social na Educação aborda a atuação do assistente social nas escolas, com foco em evasão escolar, vulnerabilidades, garantia de direitos e articulação com a rede de proteção. Ideal para assistentes sociais e profissionais da educação.'),
  ('supervisao-e-orientacao-em-educacao-infantil',
   'Em 360 horas, esta especialização prepara você para acompanhar e apoiar o trabalho pedagógico na educação infantil, com planejamento, formação de professores e relação com as famílias. Indicada para pedagogos, coordenadores e professores da primeira infância.'),
  ('supervisao-e-orientacao-escolar',
   'Com 390 horas, esta pós-graduação capacita você para coordenar o trabalho pedagógico e acompanhar o desenvolvimento dos alunos, articulando professores, famílias e gestão escolar. Ideal para pedagogos e professores que querem assumir funções de coordenação.'),
  ('supervisao-orientacao-e-inspecao-escolar',
   'Em 360 horas, esta especialização integra as funções de supervisão, orientação e inspeção escolar, com acompanhamento pedagógico, legislação educacional e apoio à gestão. Indicada para pedagogos e professores que buscam cargos técnicos e de gestão na educação.'),
  ('tea-transtorno-do-espectro-autista',
   'Com 420 horas, a pós-graduação em TEA aborda as características do Transtorno do Espectro Autista e as formas de intervenção, com estratégias para promover comunicação, aprendizagem e inclusão. Ideal para professores, mediadores, terapeutas e familiares.'),
  ('tecnologia-da-informacao',
   'Em 570 horas, a pós-graduação em Tecnologia da Informação aprofunda a gestão da infraestrutura, dos sistemas e dos serviços de TI, alinhando a tecnologia aos objetivos do negócio. Uma especialização para profissionais de TI que querem crescer para cargos de gestão.'),
  ('terapia-cognitivo-comportamental',
   'Com 570 horas, a pós-graduação em Terapia Cognitivo-Comportamental estuda os fundamentos e as técnicas da TCC para identificar e modificar pensamentos, emoções e comportamentos disfuncionais. Voltada a psicólogos e profissionais da saúde mental.'),
  ('terapia-da-constelacao-familiar-sistemica',
   'Em 570 horas, esta especialização apresenta os fundamentos da abordagem sistêmica e da constelação familiar, com foco na compreensão das dinâmicas e dos vínculos familiares. Indicada para terapeutas e profissionais que trabalham com relações humanas.'),
  ('terapia-familiar',
   'Com 570 horas, a pós-graduação em Terapia Familiar aborda a família como sistema, com técnicas de intervenção para lidar com conflitos, crises e mudanças ao longo do ciclo de vida. Ideal para psicólogos, assistentes sociais e profissionais que atendem famílias.'),
  ('transtornos-e-problemas-na-aprendizagem',
   'Em 360 horas, esta pós-graduação capacita você para identificar dislexia, TDAH, discalculia e outras dificuldades de aprendizagem, com estratégias pedagógicas para apoiar cada aluno. Indicada para professores, pedagogos e psicopedagogos.'),
  ('transtornos-globais-do-desenvolvimento-cid-f84',
   'Com 570 horas, esta especialização estuda os transtornos globais do desenvolvimento classificados no CID F84, como o autismo, com foco em características, intervenção e inclusão escolar e social. Ideal para educadores, terapeutas e profissionais da saúde.'),
  ('tutoria-em-educacao-a-distancia',
   'Em 360 horas, a pós-graduação em Tutoria em Educação a Distância prepara você para atuar como tutor, com mediação pedagógica, uso de ambientes virtuais, acompanhamento dos alunos e avaliação. Indicada para professores e profissionais que querem atuar em instituições de ensino e educação corporativa.')
) as d (slug, texto)
where c.nivel_id = n.id
  and n.slug = 'pos-graduacao'
  and c.slug = d.slug
returning c.nome, c.descricao;
