-- Descrições personalizadas dos cursos Técnicos (coluna "descricao",
-- que aparece como "Sobre o curso" na página do curso).
-- Rode inteiro no SQL Editor do Supabase. Pode rodar de novo: só sobrescreve.

update public.courses c
set descricao = d.texto
from public.course_niveis n,
(values
  ('administracao',
   'Com 880 horas, o Técnico em Administração prepara você para atuar nas rotinas administrativas de empresas, com noções de gestão de pessoas, finanças, compras, estoque, marketing e atendimento ao cliente. Uma formação versátil para quem quer entrar rápido no mercado em escritórios, comércio, indústria e serviços.'),
  ('agente-comunitario-de-saude',
   'Em 1200 horas, o Técnico em Agente Comunitário de Saúde forma profissionais para atuar na linha de frente da saúde pública, com visitas domiciliares, ações de prevenção, acolhimento e orientação às famílias. Uma formação essencial para quem trabalha ou quer trabalhar nas equipes de Saúde da Família e unidades básicas.'),
  ('analises-clinicas',
   'Com 1400 horas, o Técnico em Análises Clínicas capacita você para coletar, processar e analisar amostras biológicas, seguindo normas de biossegurança e controle de qualidade. O mercado inclui laboratórios clínicos, hospitais, clínicas, bancos de sangue e centros de pesquisa.'),
  ('automacao-industrial',
   'Em 1220 horas, o Técnico em Automação Industrial ensina a instalar, programar e manter sistemas automatizados, com CLPs, sensores, inversores e redes industriais. Uma das áreas mais promissoras da indústria moderna, com espaço em fábricas, montadoras e empresas de manutenção.'),
  ('compliance',
   'Com 960 horas, o Técnico em Compliance prepara você para apoiar as empresas no cumprimento de leis, normas e políticas internas, com controles, prevenção a fraudes, ética corporativa e proteção de dados. Uma área em crescimento em empresas privadas, instituições financeiras e escritórios.'),
  ('contabilidade',
   'Em 980 horas, o Técnico em Contabilidade ensina a registrar, organizar e interpretar informações contábeis, com rotinas fiscais, folha de pagamento e demonstrativos financeiros. Uma formação para atuar em escritórios de contabilidade, departamentos financeiros e na organização do próprio negócio.'),
  ('cuidador-de-idosos',
   'Com 1320 horas, o Técnico em Cuidador de Idosos forma profissionais para oferecer atenção integral à pessoa idosa, com cuidados de higiene, alimentação, mobilidade, estímulo à autonomia e convivência. Uma área em forte crescimento em residências, instituições de longa permanência e centros de convivência.'),
  ('edificacoes',
   'Em 1200 horas, o Técnico em Edificações prepara você para acompanhar e executar obras, interpretar projetos, fazer orçamentos, controlar materiais e garantir a qualidade e a segurança no canteiro. O mercado inclui construtoras, escritórios de engenharia e arquitetura e órgãos públicos.'),
  ('eletroeletronica',
   'Com 1440 horas, o Técnico em Eletroeletrônica forma profissionais para instalar, operar e manter sistemas elétricos e eletrônicos, unindo eletricidade, eletrônica e comandos elétricos. Uma formação ampla, com espaço em indústrias, concessionárias de energia e empresas de manutenção.'),
  ('eletromecanica',
   'Em 1600 horas, o Técnico em Eletromecânica capacita você para atuar na instalação, operação e manutenção de máquinas e sistemas eletromecânicos, integrando mecânica, eletricidade e automação. Um profissional muito procurado por indústrias de todos os setores.'),
  ('eletronica',
   'Com 1200 horas, o Técnico em Eletrônica ensina a montar, testar e reparar circuitos e equipamentos eletrônicos, com análise de componentes, instrumentos de medição e sistemas digitais. O mercado inclui assistências técnicas, indústrias, telecomunicações e empresas de automação.'),
  ('eletrotecnica',
   'Em 1520 horas, o Técnico em Eletrotécnica prepara você para projetar, instalar, operar e manter sistemas elétricos residenciais, prediais e industriais, sempre com foco em segurança e eficiência energética. Uma formação valorizada em indústrias, construtoras e concessionárias de energia.'),
  ('estetica',
   'Com 1200 horas, o Técnico em Estética forma profissionais para realizar tratamentos faciais e corporais, com avaliação estética, uso de cosméticos e equipamentos e cuidados com a biossegurança. Você pode atuar em clínicas, spas, salões de beleza ou montar o seu próprio espaço.'),
  ('farmacia',
   'Em 1600 horas, o Técnico em Farmácia capacita você para atuar na dispensação, no controle de estoque e na manipulação de medicamentos, sempre sob a supervisão do farmacêutico e com foco no atendimento seguro ao cliente. O mercado inclui drogarias, farmácias de manipulação, hospitais e distribuidoras.'),
  ('financas',
   'Com 960 horas, o Técnico em Finanças prepara você para controlar recursos financeiros, organizar fluxo de caixa, contas a pagar e a receber, orçamentos e noções de investimentos. Uma formação para atuar em departamentos financeiros, bancos, cooperativas de crédito e na gestão do próprio negócio.'),
  ('guia-de-turismo',
   'Em 1000 horas, o Técnico em Guia de Turismo forma profissionais para planejar, conduzir e acompanhar roteiros turísticos, com conhecimento de história, cultura, geografia e atendimento ao visitante. Uma carreira para quem gosta de viajar e quer atuar com agências, operadoras e turismo receptivo.'),
  ('informatica',
   'Com 1600 horas, o Técnico em Informática ensina a montar e manter computadores, instalar sistemas, configurar redes e desenvolver programas e aplicações. Uma formação completa para atuar em suporte técnico, desenvolvimento e infraestrutura de TI em empresas de todos os setores.'),
  ('logistica',
   'Em 960 horas, o Técnico em Logística capacita você para planejar e controlar o fluxo de produtos e informações, com gestão de estoques, armazenagem, transporte e distribuição. O mercado é amplo: indústrias, transportadoras, centros de distribuição, comércio e e-commerce.'),
  ('marketing',
   'Com 800 horas, o Técnico em Marketing prepara você para planejar ações de comunicação e vendas, entender o comportamento do consumidor, cuidar da imagem da marca e trabalhar com marketing digital e redes sociais. Uma formação para atuar em empresas, agências e no seu próprio negócio.'),
  ('mecanica',
   'Em 1440 horas, o Técnico em Mecânica forma profissionais para operar, ajustar e manter máquinas e equipamentos, com desenho técnico, processos de fabricação, usinagem e manutenção industrial. Um profissional essencial em indústrias, metalúrgicas e oficinas.'),
  ('mecatronica',
   'Com 1200 horas, o Técnico em Mecatrônica integra mecânica, eletrônica, programação e automação para desenvolver e manter sistemas e equipamentos automatizados. Uma formação de alta demanda na indústria 4.0, com espaço em fábricas, montadoras e empresas de tecnologia.'),
  ('meio-ambiente',
   'Em 1440 horas, o Técnico em Meio Ambiente capacita você para planejar e monitorar ações de preservação, controle da poluição, gestão de resíduos e educação ambiental. O mercado inclui indústrias, consultorias, órgãos ambientais, prefeituras e empresas de saneamento.'),
  ('mineracao',
   'Com 1300 horas, o Técnico em Mineração forma profissionais para atuar nas etapas de pesquisa, extração e beneficiamento de minérios, com foco em segurança, produtividade e responsabilidade ambiental. Uma formação valorizada em mineradoras, pedreiras e empresas de geologia.'),
  ('nutricao-e-dietetica',
   'Em 1200 horas, o Técnico em Nutrição e Dietética prepara você para apoiar o nutricionista no planejamento de cardápios, no controle de qualidade e na produção segura de alimentos. O mercado inclui hospitais, escolas, restaurantes industriais, cozinhas comerciais e indústrias de alimentos.'),
  ('papel-e-celulose',
   'O Técnico em Papel e Celulose forma profissionais para atuar na produção e no processamento de papel e celulose, do preparo da madeira ao produto final, com controle de qualidade, operação de equipamentos e práticas sustentáveis. Uma formação com espaço nas indústrias do setor florestal e de embalagens.'),
  ('protese-dentaria',
   'Com 1200 horas, o Técnico em Prótese Dentária capacita você para confeccionar, ajustar e reparar próteses dentárias com precisão, trabalhando em parceria com o cirurgião-dentista. Você pode atuar em laboratórios de prótese, clínicas odontológicas ou abrir o seu próprio laboratório.'),
  ('qualidade',
   'Em 800 horas, o Técnico em Qualidade ensina a aplicar normas, ferramentas da qualidade e indicadores, acompanhar auditorias e propor melhorias em produtos e processos. Uma formação valorizada em indústrias, empresas de serviços e instituições de saúde.'),
  ('quimica',
   'Com 1200 horas, o Técnico em Química prepara você para realizar análises laboratoriais, controlar processos químicos e apoiar o desenvolvimento de produtos, sempre com segurança. O mercado inclui indústrias químicas, farmacêuticas, de alimentos, cosméticos e laboratórios de análise.'),
  ('recursos-humanos',
   'Em 800 horas, o Técnico em Recursos Humanos capacita você para apoiar recrutamento e seleção, treinamentos, rotinas de departamento pessoal e ações de clima organizacional. Uma formação para atuar em departamentos de RH, agências de emprego e consultorias.'),
  ('redes-de-computadores',
   'Com 1000 horas, o Técnico em Redes de Computadores ensina a instalar, configurar e administrar redes locais e corporativas, com cabeamento, servidores, internet sem fio e segurança da rede. Um profissional cada vez mais necessário em empresas, provedores de internet e prestadoras de serviço de TI.'),
  ('refrigeracao-e-climatizacao',
   'Em 1540 horas, o Técnico em Refrigeração e Climatização forma profissionais para instalar, operar e manter sistemas de refrigeração e ar-condicionado residenciais, comerciais e industriais. Uma área com demanda constante, que permite trabalhar em empresas ou como prestador de serviços.'),
  ('saude-bucal',
   'Com 1200 horas, o Técnico em Saúde Bucal prepara você para atuar ao lado do cirurgião-dentista, com ações de prevenção, educação em saúde bucal, biossegurança e apoio aos procedimentos clínicos. O mercado inclui clínicas e consultórios odontológicos e as equipes de saúde bucal da rede pública.'),
  ('secretaria-escolar',
   'Em 800 horas, o Técnico em Secretaria Escolar capacita você para cuidar da gestão administrativa e acadêmica de instituições de ensino, com matrículas, documentação escolar, legislação educacional e atendimento à comunidade. Uma formação para atuar em escolas públicas e particulares.'),
  ('seguranca-do-trabalho',
   'Com 1600 horas, o Técnico em Segurança do Trabalho forma profissionais para identificar riscos, aplicar as normas regulamentadoras, conduzir treinamentos e implantar medidas de prevenção de acidentes e doenças ocupacionais. Uma área com demanda em indústrias, construtoras, hospitais e empresas de todos os portes.'),
  ('servicos-juridicos',
   'Em 800 horas, o Técnico em Serviços Jurídicos prepara você para dar suporte às rotinas jurídicas, elaborando documentos, acompanhando processos, organizando prazos e atendendo clientes. O mercado inclui escritórios de advocacia, cartórios, departamentos jurídicos de empresas e órgãos públicos.'),
  ('sistemas-de-energia-renovavel',
   'Com 1200 horas, o Técnico em Sistemas de Energia Renovável ensina a dimensionar, instalar e manter sistemas de energia solar fotovoltaica, eólica e outras fontes limpas. Uma das áreas que mais crescem no país, com espaço em empresas de energia solar, indústrias e como empreendedor.'),
  ('telecomunicacoes',
   'Em 1440 horas, o Técnico em Telecomunicações forma profissionais para instalar, operar e manter sistemas de transmissão de voz, dados e imagem, como telefonia, fibra óptica e redes sem fio. O mercado inclui operadoras, provedores de internet e empresas de infraestrutura.'),
  ('teologia',
   'Com 1000 horas, o Técnico em Teologia oferece um estudo aprofundado das Escrituras e dos fundamentos da fé cristã, com formação ministerial, liderança e aconselhamento. Uma formação para líderes, ministros e membros que querem servir com mais preparo em igrejas e projetos sociais.'),
  ('transacoes-imobiliarias',
   'Em 960 horas, o Técnico em Transações Imobiliárias prepara você para intermediar compra, venda e locação de imóveis, com avaliação, documentação, contratos e técnicas de negociação. É a formação técnica exigida para obter o registro de corretor de imóveis no CRECI.'),
  ('vendas',
   'Com 880 horas, o Técnico em Vendas ensina técnicas de negociação, atendimento, prospecção de clientes e gestão comercial para conquistar e fidelizar clientes. Uma formação para atuar no comércio, em representações, equipes comerciais e vendas online.'),
  ('veterinaria',
   'Em 1400 horas, o Técnico em Veterinária capacita você para cuidar da saúde e do bem-estar dos animais, auxiliando o médico-veterinário em atendimentos, exames, vacinação e procedimentos clínicos. O mercado inclui clínicas, hospitais veterinários, pet shops, fazendas e indústrias do setor.')
) as d (slug, texto)
where c.nivel_id = n.id
  and n.slug = 'tecnico'
  and c.slug = d.slug
returning c.nome, c.descricao;
