-- Descrições personalizadas dos cursos Técnico Por Competência (coluna
-- "descricao", que aparece como "Sobre o curso" na página do curso).
-- Rode inteiro no SQL Editor do Supabase. Pode rodar de novo: só sobrescreve.

update public.courses c
set descricao = d.texto
from public.course_niveis n,
(values
  ('administracao',
   'Você já trabalha com rotinas administrativas, mas ainda não tem o diploma? A Competência em Administração reconhece a experiência de quem atua com gestão de pessoas, finanças, compras, estoque e atendimento, e transforma essa prática em certificação técnica em 30 dias. Ideal para quem quer ser promovido ou buscar vagas melhores.'),
  ('agente-comunitario-de-saude',
   'A Competência em Agente Comunitário de Saúde certifica quem já atua na linha de frente da saúde pública, com visitas domiciliares, ações de prevenção e orientação às famílias. Em 30 dias, sua experiência no território vira formação técnica reconhecida, valorizando o seu trabalho nas equipes de saúde.'),
  ('agricultura',
   'Para quem já vive a rotina do campo, a Competência em Agricultura reconhece a experiência com cultivo, manejo do solo, irrigação e controle de pragas. Em 30 dias, você certifica o que já sabe fazer e ganha mais credibilidade para atuar em propriedades rurais, cooperativas e empresas do agro.'),
  ('agroindustria',
   'A Competência em Agroindústria certifica profissionais que já trabalham no processamento e no controle de qualidade de produtos de origem agrícola e animal. Em 30 dias, sua prática na transformação da matéria-prima rural em produtos para o mercado se torna formação técnica reconhecida.'),
  ('agropecuaria',
   'Se você já atua na produção animal e vegetal, a Competência em Agropecuária reconhece sua experiência com lavouras, criações, manejo e técnicas de produção. Em 30 dias, você conquista a certificação técnica e abre portas em fazendas, cooperativas, empresas do agronegócio e assistência rural.'),
  ('analises-clinicas',
   'A Competência em Análises Clínicas é para quem já trabalha em laboratório com coleta, processamento e análise de amostras biológicas. Em 30 dias, sua experiência com biossegurança e controle de qualidade é reconhecida com certificação técnica, valorizando sua carreira em laboratórios, hospitais e clínicas.'),
  ('automacao-industrial',
   'Para quem já atua com CLPs, sensores, inversores e sistemas automatizados, a Competência em Automação Industrial transforma a experiência prática em certificação técnica em 30 dias. Uma forma rápida de comprovar o que você já sabe e crescer dentro da indústria.'),
  ('contabilidade',
   'A Competência em Contabilidade reconhece a experiência de quem já trabalha com escrituração, rotinas fiscais, folha de pagamento e demonstrativos financeiros. Em 30 dias, sua prática em escritórios e departamentos financeiros vira certificação técnica.'),
  ('cuidador-de-idosos',
   'Se você já cuida de pessoas idosas, a Competência em Cuidador de Idosos certifica sua experiência com higiene, alimentação, mobilidade, segurança e estímulo à autonomia. Em 30 dias, você conquista a formação técnica e ganha mais confiança das famílias e das instituições.'),
  ('edificacoes',
   'A Competência em Edificações é para quem já atua em obras, acompanhando a execução, lendo projetos e controlando materiais e equipes. Em 30 dias, sua experiência no canteiro é reconhecida com certificação técnica, abrindo espaço para funções de maior responsabilidade na construção civil.'),
  ('eletroeletronica',
   'A Competência em Eletroeletrônica reconhece a experiência de quem já instala, opera e mantém sistemas elétricos e eletrônicos. Em 30 dias, você certifica sua prática e ganha mais valor no mercado, em indústrias, concessionárias e empresas de manutenção.'),
  ('eletromecanica',
   'Para quem já trabalha com manutenção de máquinas e sistemas que unem mecânica e eletricidade, a Competência em Eletromecânica transforma essa experiência em certificação técnica em 30 dias. Ideal para crescer na manutenção industrial com o diploma em mãos.'),
  ('eletronica',
   'A Competência em Eletrônica certifica quem já monta, testa e repara circuitos e equipamentos eletrônicos. Em 30 dias, sua experiência em bancada, assistência técnica ou indústria é reconhecida com formação técnica.'),
  ('eletrotecnica',
   'Se você já atua com instalações e manutenção de sistemas elétricos residenciais, prediais ou industriais, a Competência em Eletrotécnica reconhece sua experiência em 30 dias. A certificação técnica valoriza o seu trabalho e abre portas para vagas mais qualificadas.'),
  ('enfermagem',
   'A Competência em Enfermagem é voltada a quem já tem experiência comprovada nos cuidados de saúde, no apoio a procedimentos e no atendimento a pacientes. Em 30 dias, sua prática é avaliada e reconhecida com certificação técnica, valorizando sua trajetória na área da saúde.'),
  ('estetica',
   'Se você já realiza tratamentos faciais e corporais, a Competência em Estética certifica sua experiência com procedimentos, cosméticos, equipamentos e biossegurança. Em 30 dias, você conquista a formação técnica e passa mais segurança aos seus clientes.'),
  ('farmacia',
   'A Competência em Farmácia reconhece a experiência de quem já trabalha em drogarias e farmácias com dispensação, controle de estoque e atendimento. Em 30 dias, sua prática é certificada como formação técnica, valorizando sua carreira no setor farmacêutico.'),
  ('gastronomia',
   'Se você já trabalha na cozinha, a Competência em Gastronomia certifica sua experiência com técnicas culinárias, organização da produção, higiene dos alimentos e apresentação de pratos. Em 30 dias, sua prática vira certificação técnica para crescer em restaurantes, hotéis, buffets ou no seu próprio negócio.'),
  ('guia-de-turismo',
   'A Competência em Guia de Turismo é para quem já conduz grupos e roteiros turísticos e quer comprovar essa experiência. Em 30 dias, sua vivência com atendimento ao visitante, roteiros e cultura local é reconhecida com certificação técnica.'),
  ('informatica',
   'Para quem já trabalha com suporte, manutenção de computadores, sistemas ou desenvolvimento, a Competência em Informática transforma a experiência prática em certificação técnica em 30 dias. Uma forma rápida de comprovar seu conhecimento e se destacar na área de TI.'),
  ('logistica',
   'A Competência em Logística reconhece a experiência de quem já atua com estoques, armazenagem, expedição, transporte e distribuição. Em 30 dias, você certifica sua prática e ganha mais espaço para crescer em indústrias, transportadoras e centros de distribuição.'),
  ('marketing',
   'Se você já trabalha com divulgação, vendas, redes sociais ou comunicação de marcas, a Competência em Marketing certifica essa experiência em 30 dias. A formação técnica valoriza o seu trabalho em empresas, agências ou no seu próprio negócio.'),
  ('mecanica',
   'A Competência em Mecânica é para quem já opera, ajusta e mantém máquinas e equipamentos. Em 30 dias, sua experiência com manutenção, usinagem e processos de fabricação é reconhecida com certificação técnica, valorizando seu currículo na indústria.'),
  ('mecatronica',
   'Para quem já atua com sistemas que integram mecânica, eletrônica e automação, a Competência em Mecatrônica transforma essa experiência em certificação técnica em 30 dias. Ideal para comprovar sua qualificação e crescer na indústria moderna.'),
  ('meio-ambiente',
   'A Competência em Meio Ambiente reconhece a experiência de quem já atua com gestão de resíduos, monitoramento ambiental, controle da poluição ou educação ambiental. Em 30 dias, sua prática vira certificação técnica para atuar com mais respaldo em empresas, consultorias e órgãos públicos.'),
  ('metalurgia',
   'Se você já trabalha com fundição, conformação, tratamento térmico ou outros processos de transformação dos metais, a Competência em Metalurgia certifica sua experiência em 30 dias. A formação técnica valoriza sua trajetória em siderúrgicas, metalúrgicas e indústrias do setor.'),
  ('mineracao',
   'A Competência em Mineração é voltada a quem já atua nas operações de extração e beneficiamento de minérios. Em 30 dias, sua experiência com segurança, produtividade e operação de campo é reconhecida com certificação técnica.'),
  ('nutricao-e-dietetica',
   'A Competência em Nutrição e Dietética certifica quem já trabalha em cozinhas industriais, hospitalares ou escolares com produção de refeições, controle de qualidade e higiene dos alimentos. Em 30 dias, sua prática vira formação técnica.'),
  ('optica',
   'Se você já trabalha em óticas, a Competência em Óptica reconhece sua experiência com interpretação de receitas, montagem e ajuste de óculos e atendimento ao cliente. Em 30 dias, você conquista a certificação técnica e valoriza sua atuação no setor óptico.'),
  ('papel-e-celulose',
   'A Competência em Papel e Celulose é para quem já atua na produção e no processamento de papel e celulose, operando equipamentos e acompanhando a qualidade do produto. Em 30 dias, sua experiência é reconhecida com certificação técnica no setor.'),
  ('prevencao-e-combate-ao-incendio',
   'A Competência em Prevenção e Combate ao Incêndio certifica quem já atua com prevenção, análise de riscos, brigadas e combate a incêndios. Em 30 dias, sua experiência em proteger vidas e patrimônios é reconhecida com formação técnica.'),
  ('qualidade',
   'Se você já trabalha com inspeção, controle de processos, indicadores ou auditorias, a Competência em Qualidade certifica sua experiência em 30 dias. A formação técnica valoriza seu trabalho em indústrias e empresas de serviços.'),
  ('quimica',
   'A Competência em Química é para quem já atua em laboratórios ou processos industriais com análises, controle de qualidade e manuseio seguro de produtos químicos. Em 30 dias, sua prática é reconhecida com certificação técnica.'),
  ('radiologia',
   'A Competência em Radiologia é voltada a quem já tem experiência comprovada com equipamentos de diagnóstico por imagem, posicionamento de pacientes e normas de proteção radiológica. Em 30 dias, sua prática é avaliada e reconhecida com certificação técnica.'),
  ('recursos-humanos',
   'Se você já atua com recrutamento, seleção, treinamentos ou departamento pessoal, a Competência em Recursos Humanos certifica sua experiência em 30 dias. A formação técnica fortalece seu currículo para crescer na área de gestão de pessoas.'),
  ('redes-de-computadores',
   'A Competência em Redes de Computadores reconhece a experiência de quem já instala, configura e mantém redes locais e corporativas. Em 30 dias, sua prática com cabeamento, roteadores, servidores e segurança da rede vira certificação técnica.'),
  ('refrigeracao-e-climatizacao',
   'Para quem já instala e faz manutenção de ar-condicionado e sistemas de refrigeração, a Competência em Refrigeração e Climatização transforma essa experiência em certificação técnica em 30 dias. Mais credibilidade para trabalhar em empresas ou como prestador de serviços.'),
  ('saude-bucal',
   'A Competência em Saúde Bucal é para quem já atua ao lado do cirurgião-dentista, com prevenção, biossegurança e apoio aos atendimentos. Em 30 dias, sua experiência em consultórios e clínicas é reconhecida com certificação técnica.'),
  ('secretaria-escolar',
   'Se você já trabalha na secretaria de uma escola, a Competência em Secretaria Escolar certifica sua experiência com matrículas, documentação, registros escolares e atendimento à comunidade. Em 30 dias, sua prática vira formação técnica.'),
  ('seguranca-do-trabalho',
   'A Competência em Segurança do Trabalho reconhece a experiência de quem já atua com prevenção de acidentes, normas regulamentadoras, inspeções e treinamentos. Em 30 dias, sua prática é avaliada e certificada como formação técnica.'),
  ('servicos-juridicos',
   'Para quem já trabalha com rotinas jurídicas, como elaboração de documentos, acompanhamento de processos e controle de prazos, a Competência em Serviços Jurídicos certifica essa experiência em 30 dias. Ideal para crescer em escritórios de advocacia, cartórios e departamentos jurídicos.'),
  ('sistemas-de-energia-renovavel',
   'Se você já instala ou faz manutenção de sistemas de energia solar e outras fontes renováveis, a Competência em Sistemas de Energia Renovável reconhece sua experiência em 30 dias. A certificação técnica valoriza seu trabalho em uma das áreas que mais crescem no país.'),
  ('soldagem',
   'A Competência em Soldagem é para quem já executa processos de solda em diferentes materiais e quer comprovar essa experiência. Em 30 dias, sua prática com planejamento, execução e inspeção de soldas é reconhecida com certificação técnica, valorizando seu trabalho na indústria e na construção.'),
  ('telecomunicacoes',
   'A Competência em Telecomunicações certifica quem já atua com instalação e manutenção de sistemas de telefonia, fibra óptica, redes e transmissão de dados. Em 30 dias, sua experiência em operadoras e provedores vira formação técnica.'),
  ('transacoes-imobiliarias',
   'Se você já atua no mercado imobiliário com compra, venda e locação de imóveis, a Competência em Transações Imobiliárias reconhece sua experiência com documentação, contratos e negociação. Em 30 dias, sua prática é certificada como formação técnica.'),
  ('vendas',
   'A Competência em Vendas reconhece a experiência de quem já trabalha com atendimento, negociação e prospecção de clientes. Em 30 dias, você certifica sua prática comercial e ganha mais força para crescer no comércio, em representações e equipes de vendas.'),
  ('veterinaria',
   'Para quem já auxilia em clínicas, hospitais veterinários ou no campo, a Competência em Veterinária certifica sua experiência com manejo, vacinação, exames e apoio aos procedimentos. Em 30 dias, sua prática no cuidado com os animais vira formação técnica.')
) as d (slug, texto)
where c.nivel_id = n.id
  and n.slug = 'tecnico-por-competencia'
  and c.slug = d.slug
returning c.nome, c.descricao;
