-- Cursos da categoria Pós-Técnico (lista do PDF pós tecnico.pdf).
-- O texto do curso vai em "resumo": a coluna "descricao" é o texto de
-- Modalidade no "Sobre o curso". Pode rodar de novo: slug repetido é ignorado.

insert into public.courses (nivel_id, slug, nome, area, modalidade, carga_horaria, resumo)
select n.id, c.slug, c.nome, c.area, 'EAD', c.carga_horaria, c.resumo
from public.course_niveis n
cross join (values
  ('centro-de-material-e-esterilizacao', 'Especialização Técnica em Centro de Material e Esterilização', 'Saúde', '420 horas', 'A Especialização Técnica em Centro de Material e Esterilização forma profissionais capacitados a atuar na limpeza, desinfecção, esterilização e organização de materiais e equipamentos hospitalares, garantindo segurança, higiene e eficiência nos processos de saúde.'),
  ('oncologia', 'Especialização Técnica em Oncologia', 'Saúde', '400 horas', 'A Especialização Técnica em Oncologia capacita profissionais da saúde para atuar no diagnóstico, tratamento e cuidado de pacientes com câncer, integrando conhecimentos clínicos e técnicas específicas da área.'),
  ('saude-publica', 'Especialização Técnica em Saúde Pública', 'Saúde', '400 horas', 'A Especialização Técnica em Saúde Pública capacita profissionais para atuar na promoção, prevenção e cuidado em comunidades, abordando políticas de saúde, fatores epidemiológicos e ações de vigilância em saúde.'),
  ('terapia-intensiva', 'Especialização Técnica em Terapia Intensiva', 'Saúde', '400 horas', 'A Especialização Técnica em Terapia Intensiva prepara profissionais para o atendimento qualificado de pacientes em estado crítico, focando em monitoramento, suporte avançado e manejo das principais condições que exigem cuidados intensivos.'),
  ('urgencia-e-emergencia-aph', 'Especialização Técnica em Urgência e Emergência / APH', 'Saúde', '400 horas', 'A Especialização Técnica em Urgência e Emergência / Atendimento Pré-Hospitalar (APH) capacita profissionais para atuar na assistência rápida e segura a pacientes em situações críticas, tanto no local do evento quanto durante o transporte para unidades de saúde.'),
  ('saude-do-trabalhador', 'Especialização Técnica em Saúde do Trabalhador (Segurança do Trabalho)', 'Saúde', '400 horas', 'A Especialização Técnica em Saúde do Trabalhador capacita profissionais para identificar, prevenir e controlar riscos à saúde no ambiente laboral, promovendo a qualidade de vida do trabalhador.'),
  ('redacao-de-contratos', 'Especialização Técnica em Redação de Contratos', 'Negócios', '400 horas', 'A Especialização Técnica em Redação de Contratos tem como objetivo capacitar profissionais a elaborar contratos claros, objetivos e juridicamente sólidos, garantindo a proteção dos direitos e interesses das partes envolvidas.'),
  ('midias-digitais', 'Especialização Técnica em Mídias Digitais', 'Negócios', '400 horas', 'A Especialização Técnica em Mídias Digitais capacita profissionais para planejar, criar e gerenciar conteúdos em diversas plataformas digitais, utilizando estratégias de comunicação, marketing digital e análise de métricas.'),
  ('administracao-de-materiais', 'Especialização Técnica em Administração de Materiais', 'Negócios', '400 horas', 'A Especialização Técnica em Administração de Materiais capacita profissionais para gerir eficientemente os recursos materiais de uma organização, incluindo controle de estoques, classificação, codificação, compras e armazenagem.'),
  ('administracao-de-producao', 'Especialização Técnica em Administração de Produção', 'Negócios', '480 horas', 'A Especialização Técnica em Administração de Produção prepara profissionais para gerenciar e otimizar os processos produtivos, visando aumentar a eficiência, qualidade e produtividade na fabricação de bens e serviços.'),
  ('usinagem', 'Especialização Técnica em Usinagem', 'Tecnologia', '480 horas', 'A Especialização Técnica em Usinagem capacita profissionais para operar máquinas-ferramenta convencionais e CNC, realizar programações e ajustes técnicos, e garantir a produção de peças e componentes mecânicos com alta precisão.'),
  ('energia-solar-fotovoltaica', 'Especialização Técnica em Energia Solar Fotovoltaica', 'Tecnologia', '420 horas', 'A Especialização Técnica em Energia Solar Fotovoltaica capacita profissionais para projetar, instalar, operar e manter sistemas fotovoltaicos, considerando normas técnicas, segurança e conservação ambiental.'),
  ('instalacao-eletrica-predial-de-baixa-tensao', 'Especialização Técnica em Instalação Elétrica Predial de Baixa Tensão', 'Tecnologia', '420 horas', 'A Especialização Técnica em Instalação Elétrica Predial de Baixa Tensão prepara profissionais para projetar, montar e realizar manutenção em sistemas elétricos de baixa tensão em edificações residenciais, comerciais e industriais.'),
  ('controle-da-qualidade-em-farmacia', 'Especialização Técnica em Controle da Qualidade em Farmácia', 'Saúde', '400 horas', 'A Especialização Técnica em Controle da Qualidade em Farmácia forma profissionais para garantir a segurança e eficácia dos medicamentos por meio de análises e testes em matérias-primas, insumos e produtos acabados, seguindo normas e boas práticas.'),
  ('farmacia-hospitalar', 'Especialização Técnica em Farmácia Hospitalar', 'Saúde', '400 horas', 'A Especialização Técnica em Farmácia Hospitalar forma profissionais para atuar na gestão, controle e distribuição segura de medicamentos em hospitais, assegurando o uso racional e a segurança do paciente.'),
  ('manipulacao-em-laboratorio-de-farmacia', 'Especialização Técnica em Manipulação em Laboratório de Farmácia', 'Saúde', '400 horas', 'A Especialização Técnica em Manipulação em Laboratório de Farmácia é voltada para a formação de profissionais capazes de manipular medicamentos e cosméticos conforme normas de boas práticas, em laboratórios laboratoriais ou farmácias de manipulação.'),
  ('seguranca-do-trabalho-na-construcao-civil', 'Especialização Técnica em Segurança do Trabalho na Construção Civil', 'Saúde', '400 horas', 'A Especialização Técnica em Segurança do Trabalho na Construção Civil capacita profissionais para identificar e controlar riscos específicos do setor, aplicando normas regulamentadoras e promovendo a saúde e segurança nos canteiros de obras.'),
  ('higiene-ocupacional', 'Especialização Técnica em Higiene Ocupacional', 'Saúde', '400 horas', 'A Especialização Técnica em Higiene Ocupacional capacita profissionais para identificar, avaliar e controlar riscos ambientais no ambiente de trabalho, protegendo a saúde dos trabalhadores.'),
  ('prevencao-e-combate-a-incendio', 'Especialização Técnica em Prevenção e Combate a Incêndio', 'Saúde', '400 horas', 'A Especialização Técnica em Prevenção e Combate a Incêndio capacita profissionais para identificar riscos, elaborar planos de prevenção e atuar no combate eficiente a incêndios.'),
  ('informacao-e-documentacao-escolar', 'Especialização Técnica em Informação e Documentação Escolar', 'Educação', '480 horas', 'A Especialização Técnica em Informação e Documentação Escolar forma profissionais capacitados para organizar, gerenciar e preservar documentos e informações escolares, garantindo o acesso eficiente e seguro aos registros educacionais.')
) as c (slug, nome, area, carga_horaria, resumo)
where n.slug = 'pos-tecnico'
on conflict (nivel_id, slug) do nothing;
