-- Cursos da categoria Técnico Por Competência (lista do PDF competencia.pdf).
-- O texto do curso vai em "resumo": a coluna "descricao" é o texto de
-- Modalidade no "Sobre o curso". Todos duram 30 dias.
-- Pode rodar de novo: slug repetido é ignorado.

insert into public.courses (nivel_id, slug, nome, area, modalidade, duracao, carga_horaria, resumo)
select n.id, c.slug, c.nome, c.area, 'EAD', '30 dias', c.carga_horaria, c.resumo
from public.course_niveis n
cross join (values
  ('administracao', 'Competência em Administração', 'Negócios', '880 horas', 'O curso de Competência em Administração forma profissionais criativos e críticos, capazes de atuar em processos administrativos e apoiar a tomada de decisões em diferentes áreas da gestão, com foco em ética, responsabilidade social e aprendizado contínuo.'),
  ('agente-comunitario-de-saude', 'Competência em Agente Comunitário de Saúde', 'Saúde', '1200 horas', 'Forme-se para atuar na linha de frente da saúde pública! Aprenda a promover ações de prevenção, acolhimento e orientação, fortalecendo o vínculo entre comunidade e serviços de saúde.'),
  ('agricultura', 'Competência em Agricultura', 'Tecnologia', '1440 horas', 'O curso de Competência em Agricultura forma profissionais aptos a planejar, executar e acompanhar atividades agrícolas, aplicando técnicas sustentáveis de cultivo, manejo do solo, irrigação e controle de pragas. O objetivo é aumentar a produtividade com responsabilidade ambiental e eficiência na gestão rural.'),
  ('agroindustria', 'Competência em Agroindústria', 'Tecnologia', '1000 horas', 'Aprenda sobre o processamento e controle de qualidade de produtos agrícolas. Torne-se um especialista em transformar matéria-prima rural em produtos prontos para o mercado.'),
  ('agropecuaria', 'Competência em Agropecuária', 'Tecnologia', '1440 horas', 'O curso de Competência em Agropecuária forma profissionais capacitados para atuar na produção animal e vegetal, unindo técnicas de agricultura e pecuária com foco em sustentabilidade e eficiência no campo.'),
  ('analises-clinicas', 'Competência em Análises Clínicas', 'Saúde', '1400 horas', 'O curso por competência em Análises Clínicas forma profissionais capacitados a coletar, processar e analisar amostras biológicas, contribuindo para diagnósticos precisos e garantindo qualidade, segurança e ética nos procedimentos laboratoriais.'),
  ('automacao-industrial', 'Competência em Automação Industrial', 'Tecnologia', '1220 horas', 'Entre no futuro da indústria! Aprenda a projetar, instalar e manter sistemas automatizados que aumentam a eficiência e a produtividade nas fábricas.'),
  ('contabilidade', 'Competência em Contabilidade', 'Negócios', '980 horas', 'Domine a gestão financeira de empresas! Aprenda a registrar, analisar e interpretar informações contábeis para apoiar decisões estratégicas com responsabilidade e precisão.'),
  ('cuidador-de-idosos', 'Competência em Cuidador de Idosos', 'Saúde', '1320 horas', 'O curso por competência em Cuidador de Idosos forma profissionais preparados para oferecer atenção integral a pessoas idosas, promovendo cuidado, segurança, bem-estar e qualidade de vida com ética e empatia.'),
  ('edificacoes', 'Competência em Edificações', 'Tecnologia', '1200 horas', 'Construa o futuro com segurança e técnica! Aprenda a planejar, acompanhar e executar obras, com domínio de projetos, materiais e normas de construção civil.'),
  ('eletroeletronica', 'Competência em Eletroeletrônica', 'Tecnologia', '1440 horas', 'O curso de Competência em Eletroeletrônica forma profissionais aptos a instalar, operar e manter sistemas elétricos e eletrônicos, aplicando conhecimentos técnicos para garantir eficiência, segurança e inovação em diversos setores.'),
  ('eletromecanica', 'Competência em Eletromecânica', 'Tecnologia', '1600 horas', 'O curso de Competência em Eletromecânica forma profissionais capazes de atuar na instalação, operação e manutenção de sistemas eletromecânicos, integrando conhecimentos de mecânica e eletrônica para garantir eficiência, segurança e produtividade industrial.'),
  ('eletronica', 'Competência em Eletrônica', 'Tecnologia', '1200 horas', 'Aprenda a montar, testar e reparar sistemas eletrônicos de alta precisão. Seja o profissional que garante o funcionamento de equipamentos em diferentes setores da indústria.'),
  ('eletrotecnica', 'Competência em Eletrotécnica', 'Tecnologia', '1520 horas', 'O curso por Competência em Eletrotécnica forma profissionais para projetar, instalar, operar e manter sistemas elétricos, garantindo eficiência, segurança e conformidade com normas técnicas e regulamentações.'),
  ('enfermagem', 'Competência em Enfermagem', 'Saúde', '1440 horas', 'O curso por Competência em Enfermagem forma profissionais capacitados a prestar cuidados de saúde, apoiar procedimentos médicos e promover bem-estar de pacientes, atuando com ética, segurança e responsabilidade técnica.'),
  ('estetica', 'Competência em Estética', 'Saúde', '1200 horas', 'O curso por Competência em Estética forma profissionais capacitados a realizar tratamentos de beleza e bem-estar, promovendo cuidados com a pele, corpo e aparência com técnica, segurança e valorização da autoestima.'),
  ('farmacia', 'Competência em Farmácia', 'Saúde', '1600 horas', 'O curso por Competência em Farmácia forma profissionais capacitados a atuar na manipulação, dispensação e controle de medicamentos, prestando atendimento com segurança, ética e seguindo normas sanitárias.'),
  ('gastronomia', 'Competência em Gastronomia', 'Negócios', '800 horas', 'Transforme sua paixão por cozinha em carreira! Domine técnicas culinárias, gestão de cozinha e apresentação de pratos com criatividade e profissionalismo.'),
  ('guia-de-turismo', 'Competência em Guia de Turismo', 'Negócios', '1000 horas', 'O curso por Competência em Guia de Turismo forma profissionais preparados para planejar, conduzir e acompanhar atividades turísticas, oferecendo informações culturais, históricas e naturais com segurança, ética e excelente atendimento.'),
  ('informatica', 'Competência em Informática', 'Tecnologia', '1600 horas', 'O curso de Competência em Informática forma profissionais aptos a desenvolver, implementar e manter sistemas de informação, aplicativos e redes, aplicando conhecimentos em programação, suporte e tecnologia com eficiência e segurança.'),
  ('logistica', 'Competência em Logística', 'Negócios', '960 horas', 'O curso por Competência em Logística forma profissionais capacitados a planejar, organizar e controlar o fluxo de produtos, informações e serviços, otimizando recursos e garantindo eficiência na cadeia de suprimentos.'),
  ('marketing', 'Competência em Marketing', 'Negócios', '800 horas', 'Aprenda a planejar estratégias que conquistam o público! Domine técnicas de comunicação, vendas e gestão de marca para atuar no mercado com visão criativa e estratégica.'),
  ('mecanica', 'Competência em Mecânica', 'Tecnologia', '1440 horas', 'O curso de Competência em Mecânica forma profissionais aptos a projetar, operar e manter máquinas e equipamentos, aplicando conhecimentos técnicos para garantir eficiência, segurança e qualidade nos processos industriais.'),
  ('mecatronica', 'Competência em Mecatrônica', 'Tecnologia', '1200 horas', 'Forma profissionais aptos a integrar sistemas mecânicos, eletrônicos e de automação industrial. O curso desenvolve competências em manutenção, programação e controle de equipamentos automatizados, preparando para os desafios da indústria moderna.'),
  ('meio-ambiente', 'Competência em Meio Ambiente', 'Tecnologia', '1440 horas', 'O curso de Competência em Meio Ambiente forma profissionais capazes de planejar, implementar e monitorar ações de preservação e recuperação ambiental, promovendo sustentabilidade e uso consciente dos recursos naturais.'),
  ('metalurgia', 'Competência em Metalurgia', 'Tecnologia', '1200 horas', 'Atue na transformação dos metais! Aprenda processos de fundição, soldagem e tratamento térmico, garantindo qualidade e resistência aos produtos metálicos.'),
  ('mineracao', 'Competência em Mineração', 'Tecnologia', '1300 horas', 'O curso de Competência em Mineração forma profissionais aptos a planejar, operar e supervisionar atividades de extração e processamento de minerais, com foco em segurança, eficiência e sustentabilidade ambiental.'),
  ('nutricao-e-dietetica', 'Competência em Nutrição e Dietética', 'Saúde', '1200 horas', 'Aprenda a planejar e acompanhar cardápios equilibrados! Atue no controle de qualidade de alimentos, na promoção da saúde e na orientação nutricional de coletividades.'),
  ('optica', 'Competência em Óptica', 'Saúde', '1200 horas', 'Torne-se o profissional que une ciência e precisão visual! Aprenda a interpretar prescrições oftálmicas, montar e ajustar lentes e armações, além de orientar clientes na escolha de produtos ópticos com qualidade e segurança.'),
  ('papel-e-celulose', 'Competência em Papel e Celulose', 'Tecnologia', '1210 horas', 'O curso por Competência em Papel e Celulose forma profissionais aptos a atuar na produção e processamento de papel e celulose, aplicando técnicas de fabricação, controle de qualidade e sustentabilidade industrial.'),
  ('prevencao-e-combate-ao-incendio', 'Competência em Prevenção e Combate ao Incêndio', 'Saúde', '1000 horas', 'Forme-se para proteger vidas e patrimônios! Aprenda técnicas de prevenção, controle e combate a incêndios, análise de riscos, evacuação de ambientes e operação de sistemas de segurança, atuando com responsabilidade e preparo em situações de emergência.'),
  ('qualidade', 'Competência em Qualidade', 'Negócios', '800 horas', 'Garanta excelência em produtos e processos! Aprenda a aplicar normas, acompanhar auditorias e implementar melhorias contínuas em diferentes setores produtivos.'),
  ('quimica', 'Competência em Química', 'Tecnologia', '1200 horas', 'Explore o universo das transformações químicas! Aprenda a realizar análises laboratoriais, desenvolver produtos e controlar processos industriais com segurança e técnica.'),
  ('radiologia', 'Competência em Radiologia', 'Saúde', '1200 horas', 'Atue na área que une tecnologia e cuidado com a saúde! Aprenda a operar equipamentos de diagnóstico por imagem, realizar exames radiográficos e tomográficos com segurança e precisão, garantindo qualidade nos resultados e bem-estar dos pacientes.'),
  ('recursos-humanos', 'Competência em Recursos Humanos', 'Negócios', '800 horas', 'Seja o elo entre pessoas e resultados! Aprenda a recrutar talentos, gerenciar equipes, planejar treinamentos e apoiar o desenvolvimento organizacional com foco estratégico.'),
  ('redes-de-computadores', 'Competência em Redes de Computadores', 'Tecnologia', '1000 horas', 'Domine a conectividade do mundo moderno! Aprenda a instalar, configurar e administrar redes locais e corporativas com segurança e alto desempenho.'),
  ('refrigeracao-e-climatizacao', 'Competência em Refrigeração e Climatização', 'Tecnologia', '1540 horas', 'O curso de Competência em Refrigeração e Climatização forma profissionais para instalar, operar e manter sistemas de refrigeração e ar-condicionado, garantindo eficiência, segurança e conforto ambiental.'),
  ('saude-bucal', 'Competência em Saúde Bucal', 'Saúde', '1200 horas', 'Atue lado a lado com o dentista! Aprenda técnicas de prevenção, biossegurança e atendimento humanizado para garantir sorrisos mais saudáveis e confiantes.'),
  ('secretaria-escolar', 'Competência em Secretaria Escolar', 'Educação', '800 horas', 'O curso de Competência em Secretaria Escolar prepara profissionais para atuar na gestão administrativa e acadêmica de instituições de ensino, organizando documentos, atendendo a comunidade escolar e apoiando os processos educacionais com eficiência e ética.'),
  ('seguranca-do-trabalho', 'Competência em Segurança do Trabalho', 'Saúde', '1600 horas', 'O curso de Competência em Segurança do Trabalho forma profissionais capacitados a identificar riscos, implementar medidas de prevenção e promover a saúde e a segurança em ambientes laborais, seguindo normas e legislações vigentes.'),
  ('servicos-juridicos', 'Competência em Serviços Jurídicos', 'Negócios', '800 horas', 'Atue com suporte técnico no setor jurídico! Aprenda a elaborar documentos legais, acompanhar processos e organizar rotinas de escritórios, fóruns e departamentos públicos.'),
  ('sistemas-de-energia-renovavel', 'Competência em Sistemas de Energia Renovável', 'Tecnologia', '1200 horas', 'Construa o futuro da energia limpa! Aprenda a projetar, instalar e manter sistemas solares, eólicos e sustentáveis que impulsionam o progresso de forma ecológica.'),
  ('soldagem', 'Competência em Soldagem', 'Tecnologia', '1200 horas', 'Domine as técnicas que moldam o aço! Aprenda a planejar, executar e inspecionar processos de soldagem em diferentes materiais e estruturas, garantindo resistência, precisão e qualidade em projetos industriais e de construção.'),
  ('telecomunicacoes', 'Competência em Telecomunicações', 'Tecnologia', '1440 horas', 'O curso de Competência em Telecomunicações forma profissionais capacitados a instalar, operar e manter sistemas de transmissão de dados e comunicação, garantindo eficiência, qualidade e segurança nas redes de voz, vídeo e dados.'),
  ('transacoes-imobiliarias', 'Competência em Transações Imobiliárias', 'Negócios', '960 horas', 'O curso por Competência em Transações Imobiliárias forma profissionais preparados para intermediar compra, venda, locação e administração de imóveis, aplicando conhecimentos jurídicos, financeiros e de mercado com ética e segurança.'),
  ('vendas', 'Competência em Vendas', 'Negócios', '880 horas', 'Domine a arte de vender com estratégia! Aprenda técnicas de negociação, atendimento e gestão comercial para conquistar resultados e fidelizar clientes em qualquer mercado.'),
  ('veterinaria', 'Competência em Veterinária', 'Saúde', '1400 horas', 'O curso por Competência em Veterinária forma profissionais capacitados a cuidar da saúde e bem-estar de animais, realizando procedimentos preventivos, assistenciais e de manejo com ética, segurança e responsabilidade técnica.')
) as c (slug, nome, area, carga_horaria, resumo)
where n.slug = 'tecnico-por-competencia'
on conflict (nivel_id, slug) do nothing;
