-- Cursos da categoria Técnico (lista do PDF tecnicos.pdf).
-- O texto do curso vai em "resumo": a coluna "descricao" é o texto de
-- Modalidade no "Sobre o curso". Pode rodar de novo: slug repetido é ignorado.

insert into public.courses (nivel_id, slug, nome, area, modalidade, carga_horaria, resumo)
select n.id, c.slug, c.nome, c.area, 'EAD', c.carga_horaria, c.resumo
from public.course_niveis n
cross join (values
  ('administracao', 'Técnico em Administração', 'Negócios', '880 horas', 'O curso Técnico em Administração forma profissionais criativos e críticos, capazes de atuar em processos administrativos e apoiar a tomada de decisões em diferentes áreas da gestão, com foco em ética, responsabilidade social e aprendizado contínuo.'),
  ('agente-comunitario-de-saude', 'Técnico em Agente Comunitário de Saúde', 'Saúde', '1200 horas', 'Forme-se para atuar na linha de frente da saúde pública! Aprenda a promover ações de prevenção, acolhimento e orientação, fortalecendo o vínculo entre comunidade e serviços de saúde.'),
  ('analises-clinicas', 'Técnico em Análises Clínicas', 'Saúde', '1400 horas', 'O curso Técnico em Análises Clínicas forma profissionais capacitados a coletar, processar e analisar amostras biológicas, contribuindo para diagnósticos precisos e garantindo qualidade, segurança e ética nos procedimentos laboratoriais.'),
  ('automacao-industrial', 'Técnico em Automação Industrial', 'Tecnologia', '1220 horas', 'Entre no futuro da indústria! Aprenda a projetar, instalar e manter sistemas automatizados que aumentam a eficiência e a produtividade nas fábricas.'),
  ('compliance', 'Técnico em Compliance', 'Negócios', '960 horas', 'O curso Técnico em Compliance forma profissionais capazes de garantir que empresas e organizações sigam normas, regulamentos e boas práticas, promovendo ética, transparência e gestão de riscos corporativos.'),
  ('contabilidade', 'Técnico em Contabilidade', 'Negócios', '980 horas', 'Domine a gestão financeira de empresas! Aprenda a registrar, analisar e interpretar informações contábeis para apoiar decisões estratégicas com responsabilidade e precisão.'),
  ('cuidador-de-idosos', 'Técnico em Cuidador de Idosos', 'Saúde', '1320 horas', 'O curso Técnico em Cuidador de Idosos forma profissionais preparados para oferecer atenção integral a pessoas idosas, promovendo cuidado, segurança, bem-estar e qualidade de vida com ética e empatia.'),
  ('edificacoes', 'Técnico em Edificações', 'Tecnologia', '1200 horas', 'Construa o futuro com segurança e técnica! Aprenda a planejar, acompanhar e executar obras, com domínio de projetos, materiais e normas de construção civil.'),
  ('eletroeletronica', 'Técnico em Eletroeletrônica', 'Tecnologia', '1440 horas', 'O curso Técnico em Eletroeletrônica forma profissionais aptos a instalar, operar e manter sistemas elétricos e eletrônicos, aplicando conhecimentos técnicos para garantir eficiência, segurança e inovação em diversos setores.'),
  ('eletromecanica', 'Técnico em Eletromecânica', 'Tecnologia', '1600 horas', 'O curso Técnico em Eletromecânica forma profissionais capazes de atuar na instalação, operação e manutenção de sistemas eletromecânicos, integrando conhecimentos de mecânica e eletrônica para garantir eficiência, segurança e produtividade industrial.'),
  ('eletronica', 'Técnico em Eletrônica', 'Tecnologia', '1200 horas', 'Aprenda a montar, testar e reparar sistemas eletrônicos de alta precisão. Seja o profissional que garante o funcionamento de equipamentos em diferentes setores da indústria.'),
  ('eletrotecnica', 'Técnico em Eletrotécnica', 'Tecnologia', '1520 horas', 'O curso Técnico em Eletrotécnica forma profissionais para projetar, instalar, operar e manter sistemas elétricos, garantindo eficiência, segurança e conformidade com normas técnicas e regulamentações.'),
  ('estetica', 'Técnico em Estética', 'Saúde', '1200 horas', 'O curso Técnico em Estética forma profissionais capacitados a realizar tratamentos de beleza e bem-estar, promovendo cuidados com a pele, corpo e aparência com técnica, segurança e valorização da autoestima.'),
  ('farmacia', 'Técnico em Farmácia', 'Saúde', '1600 horas', 'O curso Técnico em Farmácia forma profissionais capacitados a atuar na manipulação, dispensação e controle de medicamentos, prestando atendimento com segurança, ética e seguindo normas sanitárias.'),
  ('financas', 'Técnico em Finanças', 'Negócios', '960 horas', 'O curso Técnico em Finanças forma profissionais preparados para gerir recursos financeiros, analisar investimentos, controlar orçamento e apoiar decisões estratégicas, com foco em eficiência, ética e sustentabilidade econômica.'),
  ('guia-de-turismo', 'Técnico em Guia de Turismo', 'Negócios', '1000 horas', 'O curso Técnico em Guia de Turismo forma profissionais preparados para planejar, conduzir e acompanhar atividades turísticas, oferecendo informações culturais, históricas e naturais com segurança, ética e excelente atendimento.'),
  ('informatica', 'Técnico em Informática', 'Tecnologia', '1600 horas', 'O curso Técnico em Informática forma profissionais aptos a desenvolver, implementar e manter sistemas de informação, aplicativos e redes, aplicando conhecimentos em programação, suporte e tecnologia com eficiência e segurança.'),
  ('logistica', 'Técnico em Logística', 'Negócios', '960 horas', 'O curso Técnico em Logística forma profissionais capacitados a planejar, organizar e controlar o fluxo de produtos, informações e serviços, otimizando recursos e garantindo eficiência na cadeia de suprimentos.'),
  ('marketing', 'Técnico em Marketing', 'Negócios', '800 horas', 'Aprenda a planejar estratégias que conquistam o público! Domine técnicas de comunicação, vendas e gestão de marca para atuar no mercado com visão criativa e estratégica.'),
  ('mecanica', 'Técnico em Mecânica', 'Tecnologia', '1440 horas', 'O curso Técnico em Mecânica forma profissionais aptos a projetar, operar e manter máquinas e equipamentos, aplicando conhecimentos técnicos para garantir eficiência, segurança e qualidade nos processos industriais.'),
  ('mecatronica', 'Técnico em Mecatrônica', 'Tecnologia', '1200 horas', 'Forma profissionais aptos a integrar sistemas mecânicos, eletrônicos e de automação industrial. O curso desenvolve competências em manutenção, programação e controle de equipamentos automatizados, preparando para os desafios da indústria moderna.'),
  ('meio-ambiente', 'Técnico em Meio Ambiente', 'Tecnologia', '1440 horas', 'O curso Técnico em Meio Ambiente forma profissionais capazes de planejar, implementar e monitorar ações de preservação e recuperação ambiental, promovendo sustentabilidade e uso consciente dos recursos naturais.'),
  ('mineracao', 'Técnico em Mineração', 'Tecnologia', '1300 horas', 'O curso Técnico em Mineração forma profissionais aptos a planejar, operar e supervisionar atividades de extração e processamento de minerais, com foco em segurança, eficiência e sustentabilidade ambiental.'),
  ('nutricao-e-dietetica', 'Técnico em Nutrição e Dietética', 'Saúde', '1200 horas', 'Aprenda a planejar e acompanhar cardápios equilibrados! Atue no controle de qualidade de alimentos, na promoção da saúde e na orientação nutricional de coletividades.'),
  ('papel-e-celulose', 'Técnico em Papel e Celulose', 'Tecnologia', '', 'O curso Técnico em Papel e Celulose forma profissionais aptos a atuar na produção e processamento de papel e celulose, aplicando técnicas de fabricação, controle de qualidade e sustentabilidade industrial.'),
  ('protese-dentaria', 'Técnico em Prótese Dentária', 'Saúde', '1200 horas', 'Transforme sorrisos com precisão! Desenvolva habilidades para confeccionar, reparar e ajustar próteses dentárias, atuando lado a lado com cirurgiões-dentistas.'),
  ('qualidade', 'Técnico em Qualidade', 'Negócios', '800 horas', 'Garanta excelência em produtos e processos! Aprenda a aplicar normas, acompanhar auditorias e implementar melhorias contínuas em diferentes setores produtivos.'),
  ('quimica', 'Técnico em Química', 'Tecnologia', '1200 horas', 'Explore o universo das transformações químicas! Aprenda a realizar análises laboratoriais, desenvolver produtos e controlar processos industriais com segurança e técnica.'),
  ('recursos-humanos', 'Técnico em Recursos Humanos', 'Negócios', '800 horas', 'Seja o elo entre pessoas e resultados! Aprenda a recrutar talentos, gerenciar equipes, planejar treinamentos e apoiar o desenvolvimento organizacional com foco estratégico.'),
  ('redes-de-computadores', 'Técnico em Redes de Computadores', 'Tecnologia', '1000 horas', 'Domine a conectividade do mundo moderno! Aprenda a instalar, configurar e administrar redes locais e corporativas com segurança e alto desempenho.'),
  ('refrigeracao-e-climatizacao', 'Técnico em Refrigeração e Climatização', 'Tecnologia', '1540 horas', 'O curso Técnico em Refrigeração e Climatização forma profissionais para instalar, operar e manter sistemas de refrigeração e ar-condicionado, garantindo eficiência, segurança e conforto ambiental.'),
  ('saude-bucal', 'Técnico em Saúde Bucal', 'Saúde', '1200 horas', 'Atue lado a lado com o dentista! Aprenda técnicas de prevenção, biossegurança e atendimento humanizado para garantir sorrisos mais saudáveis e confiantes.'),
  ('secretaria-escolar', 'Técnico em Secretaria Escolar', 'Educação', '800 horas', 'O curso Técnico em Secretaria Escolar prepara profissionais para atuar na gestão administrativa e acadêmica de instituições de ensino, organizando documentos, atendendo a comunidade escolar e apoiando os processos educacionais com eficiência e ética.'),
  ('seguranca-do-trabalho', 'Técnico em Segurança do Trabalho', 'Saúde', '1600 horas', 'O curso Técnico em Segurança do Trabalho forma profissionais capacitados a identificar riscos, implementar medidas de prevenção e promover a saúde e a segurança em ambientes laborais, seguindo normas e legislações vigentes.'),
  ('servicos-juridicos', 'Técnico em Serviços Jurídicos', 'Negócios', '800 horas', 'Atue com suporte técnico no setor jurídico! Aprenda a elaborar documentos legais, acompanhar processos e organizar rotinas de escritórios, fóruns e departamentos públicos.'),
  ('sistemas-de-energia-renovavel', 'Técnico em Sistemas de Energia Renovável', 'Tecnologia', '1200 horas', 'Construa o futuro da energia limpa! Aprenda a projetar, instalar e manter sistemas solares, eólicos e sustentáveis que impulsionam o progresso de forma ecológica.'),
  ('telecomunicacoes', 'Técnico em Telecomunicações', 'Tecnologia', '1440 horas', 'O curso Técnico em Telecomunicações forma profissionais capacitados a instalar, operar e manter sistemas de transmissão de dados e comunicação, garantindo eficiência, qualidade e segurança nas redes de voz, vídeo e dados.'),
  ('teologia', 'Técnico em Teologia', 'Educação', '1000 horas', 'Capacita para o estudo aprofundado das Escrituras, fundamentos da fé cristã e formação ministerial. Desenvolve liderança, ética e preparo para atuação em comunidades religiosas e projetos sociais.'),
  ('transacoes-imobiliarias', 'Técnico em Transações Imobiliárias', 'Negócios', '960 horas', 'O curso Técnico em Transações Imobiliárias forma profissionais preparados para intermediar compra, venda, locação e administração de imóveis, aplicando conhecimentos jurídicos, financeiros e de mercado com ética e segurança.'),
  ('vendas', 'Técnico em Vendas', 'Negócios', '880 horas', 'Domine a arte de vender com estratégia! Aprenda técnicas de negociação, atendimento e gestão comercial para conquistar resultados e fidelizar clientes em qualquer mercado.'),
  ('veterinaria', 'Técnico em Veterinária', 'Saúde', '1400 horas', 'O curso Técnico em Veterinária forma profissionais capacitados a cuidar da saúde e bem-estar de animais, realizando procedimentos preventivos, assistenciais e de manejo com ética, segurança e responsabilidade técnica.')
) as c (slug, nome, area, carga_horaria, resumo)
where n.slug = 'tecnico'
on conflict (nivel_id, slug) do nothing;
