import type { TraitWeights } from "./types.ts";

/* Perfil interno de afinidade de cada curso, chaveado pelo slug REAL do curso
   (tabela `courses` do Supabase). Nada de nome, imagem ou URL aqui: esses
   dados continuam vindo da fonte central (lib/data/courses.ts).

   Escala 1–5 por dimensão; dimensão ausente = 0. Só a proporção entre as
   dimensões importa (a comparação é por cosseno), então um curso com muitos
   5 não leva vantagem sobre um com poucos.

   Curso cadastrado no admin sem entrada aqui NÃO é recomendado (e gera um
   aviso no log do servidor) — melhor ficar de fora do que ser recomendado com
   um perfil inventado. */
export const COURSE_AFFINITY_PROFILES: Record<string, TraitWeights> = {
  /* ---------------- Graduação ---------------- */
  "gestao-em-ti": { technology: 5, management: 4, strategy: 4, leadership: 3, analysis: 2, organization: 2 },

  /* ---------------- Direito e justiça ---------------- */
  "direito-administrativo": { justice: 5, organization: 3, management: 2, social: 2, communication: 2 },
  "direito-ambiental": { justice: 5, social: 4, science: 2, communication: 2 },
  "direito-constitucional": { justice: 5, social: 3, communication: 3, strategy: 2, analysis: 2 },
  "direito-de-familia": { justice: 5, people: 3, behavior: 3, care: 2, communication: 2 },
  "direito-de-transito": { justice: 5, social: 3, organization: 3, practical: 1 },
  "direito-do-trabalho-e-processual-trabalhista": { justice: 5, people: 3, organization: 3, communication: 2, social: 2 },
  "direito-educacional": { justice: 5, education: 4, social: 2, organization: 2 },
  "direito-eleitoral": { justice: 5, communication: 3, social: 3, strategy: 2 },
  "direito-empresarial": { justice: 5, management: 3, strategy: 3, organization: 2, analysis: 1 },
  "direito-imobiliario": { justice: 5, organization: 3, management: 2, people: 2, strategy: 1 },
  "direito-penal-e-processual-penal": { justice: 5, communication: 3, behavior: 2, social: 2, analysis: 2 },
  "direito-penal-militar": { justice: 5, organization: 3, leadership: 2, social: 2, practical: 1 },
  "direito-previdenciario": { justice: 5, social: 3, organization: 3, analysis: 2, care: 1 },
  "direito-processual-civil": { justice: 5, organization: 4, communication: 3, analysis: 2 },
  "direito-publico-constitucional-administrativo-e-tributario": { justice: 5, organization: 3, analysis: 3, management: 2, social: 2 },
  "direito-tributario": { justice: 5, analysis: 4, organization: 3, strategy: 2, management: 1 },
  "direitos-humanos-e-pericia-criminal": { justice: 5, social: 4, science: 3, analysis: 3, practical: 2 },
  compliance: { justice: 5, organization: 5, analysis: 3, management: 2, strategy: 2 },
  criminologia: { justice: 5, behavior: 4, social: 3, analysis: 3, science: 1 },
  "mba-em-arbitragem-conciliacao-e-mediacao": { justice: 4, people: 4, communication: 4, behavior: 2, social: 1 },
  "mba-em-compliance-e-gestao-de-riscos": { justice: 4, organization: 4, analysis: 4, strategy: 3, management: 2 },
  "seguranca-publica": { justice: 4, social: 4, leadership: 3, practical: 3, organization: 2 },
  "seguranca-publica-e-cidadania": { social: 5, justice: 4, people: 2, practical: 2, leadership: 2, education: 1 },
  "relacoes-internacionais": { strategy: 4, communication: 4, social: 3, justice: 3, people: 2 },

  /* ---------------- Gestão, negócios e pessoas ---------------- */
  "administracao-publica": { management: 4, organization: 4, social: 3, justice: 3, strategy: 3, leadership: 2 },
  agronegocios: { management: 4, strategy: 4, practical: 3, science: 2, analysis: 2, social: 1 },
  "gestao-bancaria-e-negocios": { management: 4, analysis: 4, strategy: 3, people: 2, organization: 2 },
  "gestao-da-qualidade": { organization: 5, management: 4, analysis: 3, practical: 2, strategy: 2 },
  "gestao-de-recursos-humanos": { people: 5, management: 4, behavior: 3, organization: 2, leadership: 2 },
  "gestao-e-planejamento-de-projetos-sociais": { social: 5, management: 4, organization: 3, people: 3, strategy: 2 },
  "gestao-estrategica-de-pessoas": { people: 5, strategy: 4, leadership: 3, management: 3, behavior: 2 },
  "lideranca-e-desenvolvimento-de-equipes": { leadership: 5, people: 4, behavior: 3, communication: 3, management: 2, education: 1 },
  "mba-em-coaching": { behavior: 4, people: 4, education: 3, leadership: 3, communication: 3, care: 1 },
  "mba-em-gestao-aplicada-a-engenharia": { management: 4, practical: 4, organization: 3, analysis: 3, technology: 2, leadership: 2 },
  "mba-em-gestao-comercial-e-vendas": { people: 4, communication: 4, strategy: 4, management: 3, leadership: 2 },
  "mba-em-gestao-de-departamento-pessoal-e-relacoes-trabalhistas": { organization: 5, people: 3, justice: 3, management: 3, analysis: 1 },
  "mba-em-gestao-de-eventos": { organization: 4, creativity: 4, people: 3, management: 3, communication: 3, practical: 2 },
  "mba-em-gestao-de-negocios-imobiliarios": { people: 4, management: 3, strategy: 3, communication: 3, justice: 1 },
  "mba-em-gestao-de-obras-qualidade-e-desempenho-das-construcoes": { practical: 5, organization: 4, management: 4, analysis: 2, technology: 2 },
  "mba-em-gestao-de-pessoas-e-lideranca": { leadership: 5, people: 5, management: 3, behavior: 2, communication: 2 },
  "mba-em-gestao-de-processos": { organization: 5, management: 4, analysis: 3, strategy: 2, technology: 1 },
  "mba-em-gestao-de-projetos": { management: 5, organization: 4, leadership: 3, strategy: 3, people: 1 },
  "mba-em-gestao-de-supply-chain": { organization: 4, management: 4, analysis: 3, strategy: 3, practical: 2, technology: 1 },
  "mba-em-gestao-estrategica-de-cooperativas": { management: 4, strategy: 4, social: 3, people: 3, leadership: 2 },
  "mba-em-gestao-estrategica-em-compras": { strategy: 4, management: 4, analysis: 3, organization: 3, people: 2 },
  "mba-em-gestao-ambiental-e-sustentavel": { social: 4, management: 4, science: 3, strategy: 3, organization: 2 },
  "mba-em-negocios-internacionais-e-comercio-exterior": { strategy: 5, management: 3, communication: 3, people: 2, analysis: 2, justice: 1 },
  "mba-em-planejamento-e-gestao-no-transito": { organization: 4, social: 4, management: 3, strategy: 3, justice: 2, analysis: 1 },
  "mba-em-startups-e-inovacao": { creativity: 5, strategy: 4, technology: 4, leadership: 3, management: 2 },
  "servico-social-e-convivencia-familiar": { social: 5, care: 4, people: 4, behavior: 3, justice: 2 },

  /* ---------------- Finanças e contabilidade ---------------- */
  "mba-em-administracao-financeira-e-orcamentaria": { organization: 5, analysis: 4, management: 4, strategy: 3, leadership: 2 },
  "mba-em-contabilidade-gerencial": { analysis: 5, organization: 5, management: 3, strategy: 2 },
  "mba-em-controladoria-e-financas": { analysis: 5, organization: 4, strategy: 3, management: 3 },
  "mba-em-gestao-de-custo-e-financas": { analysis: 5, management: 3, organization: 3, practical: 3, strategy: 2 },
  "mba-em-gestao-de-seguros-e-previdencia-privada": { analysis: 4, management: 3, people: 3, strategy: 3, organization: 2 },
  "mba-em-gestao-financeira-e-controladoria": { analysis: 5, management: 4, organization: 4, strategy: 3, leadership: 1 },
  "mba-em-gestao-fiscal-e-tributaria": { organization: 5, analysis: 4, justice: 3, management: 3 },
  "mba-em-educacao-financeira": { education: 4, analysis: 4, communication: 3, social: 2, strategy: 2 },
  "matematica-financeira-e-estatistica": { analysis: 5, organization: 3, strategy: 3, technology: 2, education: 1 },
  "pericia-e-auditoria-contabil": { analysis: 5, organization: 5, justice: 3, practical: 1 },
  "pericia-economico-financeira": { analysis: 5, organization: 4, justice: 3, strategy: 2 },

  /* ---------------- Comunicação e marketing ---------------- */
  "comunicacao-e-oratoria": { communication: 5, people: 3, leadership: 2, creativity: 2, education: 1 },
  "mba-em-assessoria-de-comunicacao": { communication: 5, strategy: 3, creativity: 3, people: 3, management: 1 },
  "mba-em-comunicacao-eleitoral-e-marketing-politico": { communication: 5, strategy: 4, creativity: 3, social: 2, justice: 1 },
  "mba-em-e-commerce": { technology: 4, strategy: 4, management: 3, creativity: 2, analysis: 2, communication: 2 },
  "mba-em-gestao-de-marketing-digital": { strategy: 4, creativity: 4, communication: 4, technology: 3, analysis: 2 },
  "mba-em-jornalismo-digital": { communication: 5, creativity: 4, technology: 3, social: 2, analysis: 1 },
  "mba-em-marketing-de-varejo-gestao-estrategias-e-negocios": { strategy: 4, management: 4, communication: 3, creativity: 3, people: 2, analysis: 2 },
  "mba-em-marketing-digital-e-comunicacao-online": { communication: 5, creativity: 4, technology: 3, strategy: 3, people: 1 },

  /* ---------------- Tecnologia, dados e engenharias ---------------- */
  "tecnologia-da-informacao": { technology: 5, analysis: 4, practical: 4, organization: 2, creativity: 2 },
  "seguranca-da-informacao": { technology: 5, analysis: 4, organization: 4, practical: 3, justice: 2 },
  "gestao-de-riscos-e-ciberseguranca": { technology: 5, analysis: 4, strategy: 4, organization: 3, justice: 2 },
  "estatistica-aplicada": { analysis: 5, technology: 4, science: 3, organization: 2 },
  "engenharia-ambiental": { science: 4, practical: 4, social: 4, analysis: 3, technology: 2 },
  "engenharia-ambiental-e-saneamento-basico": { practical: 5, science: 4, social: 4, analysis: 3, technology: 2, organization: 1 },
  "engenharia-sanitaria-e-ambiental": { practical: 5, social: 5, science: 4, analysis: 3, organization: 2 },
  "engenharia-da-qualidade": { organization: 5, analysis: 4, practical: 4, technology: 2, management: 2 },
  "engenharia-de-manutencao": { practical: 5, technology: 4, organization: 4, analysis: 3 },
  "engenharia-de-producao": { organization: 4, analysis: 4, management: 4, practical: 4, technology: 2, strategy: 2 },
  "engenharia-de-seguranca-do-trabalho": { practical: 5, organization: 4, justice: 3, care: 3, science: 2 },
  "engenharia-de-suprimentos": { organization: 4, management: 4, analysis: 4, strategy: 3, practical: 2 },
  "engenharia-logistica": { organization: 5, analysis: 4, management: 3, strategy: 3, practical: 3, technology: 2 },
  "geologia-e-hidrologia": { science: 5, practical: 4, analysis: 4, social: 2 },

  /* ---------------- Psicologia, comportamento e terapias ---------------- */
  "analise-do-comportamento-aplicada-aba-a-individuos-com-transtorno-do-espectro-autista-tea": { behavior: 5, care: 4, education: 3, science: 3, practical: 3, social: 1 },
  arteterapia: { creativity: 5, care: 4, behavior: 4, people: 2 },
  "avaliacao-psicologica-e-psicodiagnostico": { behavior: 5, analysis: 4, science: 3, care: 2 },
  "comportamento-humano-e-neurociencia": { behavior: 5, science: 5, analysis: 2, education: 1 },
  "diagnostico-e-avaliacao-psicologica": { behavior: 5, analysis: 4, science: 3, care: 3 },
  "medicinas-e-terapias-alternativas": { care: 5, behavior: 3, practical: 3, creativity: 2, science: 2 },
  "neuropsicologia-clinica": { behavior: 5, science: 5, care: 3, analysis: 3 },
  "psicanalise-clinica": { behavior: 5, care: 4, people: 3, communication: 2, creativity: 1 },
  "psicologia-clinica": { behavior: 5, care: 5, people: 3, communication: 2, science: 2 },
  "psicologia-clinica-e-institucional": { behavior: 5, care: 4, people: 3, social: 3, management: 1 },
  "psicologia-hospitalar": { behavior: 5, care: 5, science: 3, people: 2, practical: 2 },
  "psicologia-organizacional-e-do-trabalho": { people: 5, behavior: 4, management: 3, leadership: 2, organization: 2 },
  "tea-transtorno-do-espectro-autista": { care: 5, behavior: 4, education: 3, science: 3, social: 2 },
  "terapia-cognitivo-comportamental": { behavior: 5, care: 4, science: 3, analysis: 2, education: 2 },
  "terapia-da-constelacao-familiar-sistemica": { behavior: 4, care: 4, people: 4, creativity: 2, social: 1 },
  "terapia-familiar": { behavior: 5, people: 4, care: 4, communication: 3, social: 2 },
  "transtornos-globais-do-desenvolvimento-cid-f84": { behavior: 4, science: 4, care: 4, education: 3, analysis: 2 },

  /* ---------------- Saúde e cuidado ---------------- */
  "atencao-e-cuidados-com-idosos": { care: 5, people: 3, practical: 3, social: 2, science: 1 },
  "auditoria-em-saude": { organization: 5, analysis: 4, care: 2, science: 2, justice: 2, management: 2 },
  "biomedicina-estetica": { practical: 5, science: 4, care: 3, creativity: 2 },
  "cuidados-paliativos": { care: 5, people: 3, behavior: 3, science: 2, social: 1 },
  "enfermagem-do-trabalho-e-saude-ocupacional": { care: 4, practical: 4, organization: 3, science: 3, social: 2 },
  "enfermagem-em-urgencia-e-emergencia": { care: 5, practical: 5, science: 3, leadership: 2, organization: 1 },
  "enfermagem-oncologica": { care: 5, science: 4, practical: 4, people: 2, behavior: 1 },
  "estetica-corporal-e-facial": { practical: 5, care: 4, creativity: 3, people: 3, science: 2 },
  "estetica-e-cosmetologia": { practical: 4, care: 4, science: 3, creativity: 3, people: 2 },
  "farmacia-clinica-e-hospitalar": { science: 5, care: 4, organization: 3, practical: 3, analysis: 2 },
  "farmacologia-clinica-aplicada-a-prescricao-farmaceutica": { science: 5, care: 4, analysis: 3, practical: 2, justice: 1 },
  "fisioterapia-aplicada-as-atividades-fisicas": { practical: 5, care: 4, science: 4, people: 2, education: 1 },
  "fisioterapia-em-geriatria-e-gerontologia": { care: 5, practical: 4, science: 3, people: 3 },
  "gestao-hospitalar": { management: 5, organization: 4, care: 3, leadership: 3, strategy: 2 },
  "mba-em-gestao-da-saude-publica": { management: 4, social: 4, care: 3, organization: 3, strategy: 2 },
  "mba-em-gestao-de-clinicas-e-consultorios-veterinarios": { management: 4, care: 3, organization: 3, science: 2, people: 2, strategy: 2 },
  "mba-em-gestao-de-drogaria-e-farmacia": { management: 4, care: 3, organization: 3, science: 2, people: 2 },
  microbiologia: { science: 5, analysis: 4, practical: 3, organization: 2 },
  "nutricao-esportiva": { science: 4, care: 4, practical: 4, education: 2, people: 1 },

  /* ---------------- Educação, docência e inclusão ---------------- */
  antropologia: { social: 5, behavior: 4, analysis: 3, communication: 2, science: 2 },
  "atendimento-educacional-especializado-com-enfase-em-autismo": { education: 5, care: 4, social: 4, behavior: 3, practical: 2 },
  "ciencias-da-religiao-com-enfase-em-docencia-do-ensino-superior": { education: 5, behavior: 3, social: 3, communication: 3, justice: 1 },
  "didatica-do-ensino-de-lingua-portuguesa-inglesa-e-espanhola": { education: 5, communication: 5, creativity: 2, people: 2 },
  "docencia-em-enfermagem": { education: 5, care: 4, science: 3, communication: 3, practical: 2 },
  "educacao-ambiental-e-sustentabilidade": { social: 5, education: 4, science: 3, communication: 2, creativity: 1 },
  "educacao-especial-e-inclusiva": { education: 5, social: 4, care: 4, behavior: 2, creativity: 1 },
  "educacao-especial-inclusiva-e-transtorno-do-espectro-autista-tea": { education: 5, care: 4, behavior: 4, social: 3 },
  "ensino-da-literatura-africana-e-indigena": { education: 5, social: 4, communication: 3, creativity: 3 },
  "expressoes-artisticas-e-suas-representacoes": { creativity: 5, communication: 3, education: 3, social: 2 },
  "gestao-educacional-com-foco-na-inclusao": { education: 4, management: 4, social: 4, leadership: 3, organization: 2 },
  libras: { communication: 5, social: 4, education: 4, people: 3, practical: 2 },
  ludopedagogia: { education: 5, creativity: 5, care: 2, people: 2, practical: 2 },
  "metodologia-do-ensino-de-ingles": { education: 5, communication: 5, creativity: 2, organization: 1 },
  "metodologia-do-ensino-de-lingua-portuguesa": { education: 5, communication: 5, organization: 2, social: 1 },
  "metodologia-do-ensino-linguistico": { education: 5, communication: 4, analysis: 3, behavior: 1 },
  "metodologia-do-ensino-superior-nas-varias-modalidades": { education: 5, communication: 4, organization: 3, technology: 2, strategy: 1 },
  "metodologias-ativas-e-pratica-docente": { education: 5, creativity: 4, people: 3, practical: 3, communication: 2 },
  "metodologias-ativas-e-tecnologias-educacionais": { education: 5, technology: 4, creativity: 4, communication: 2 },
  neuroeducacao: { education: 5, behavior: 4, science: 4, analysis: 2 },
  "neuropsicopedagogia-clinica": { behavior: 5, education: 4, science: 4, care: 3, analysis: 2 },
  "orientacao-educacional": { education: 5, people: 4, behavior: 3, care: 3, communication: 2 },
  "projetos-pedagogicos": { education: 5, organization: 4, creativity: 3, management: 3, strategy: 2 },
  "psicologia-da-educacao": { behavior: 5, education: 5, science: 2, care: 2, people: 2 },
  psicomotricidade: { practical: 4, education: 4, care: 4, science: 3, behavior: 3 },
  "psicomotricidade-e-ludopedagogia": { education: 5, practical: 4, creativity: 4, care: 3, behavior: 2 },
  "psicomotricidade-na-educacao-infantil": { education: 5, practical: 4, care: 4, behavior: 3, creativity: 2 },
  "psicopedagogia-clinica-e-institucional": { education: 5, behavior: 4, care: 4, analysis: 2, people: 2 },
  "psicopedagogia-escolar": { education: 5, behavior: 4, people: 3, care: 3, organization: 1 },
  "servico-social-na-educacao": { social: 5, education: 4, care: 3, people: 3, justice: 2 },
  "supervisao-e-orientacao-em-educacao-infantil": { education: 5, organization: 4, leadership: 3, care: 3, people: 2 },
  "supervisao-e-orientacao-escolar": { education: 5, leadership: 4, organization: 4, people: 3, management: 2 },
  "supervisao-orientacao-e-inspecao-escolar": { organization: 5, education: 4, leadership: 3, justice: 3, management: 3 },
  "transtornos-e-problemas-na-aprendizagem": { education: 5, behavior: 4, care: 3, science: 3, analysis: 2 },
  "tutoria-em-educacao-a-distancia": { education: 5, technology: 4, communication: 4, people: 3, organization: 2 },
};
